# Generated by Django 3.0.4 on 2020-04-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightactivities',
            name='type_id',
        ),
        migrations.AddField(
            model_name='flightactivities',
            name='activity',
            field=models.CharField(choices=[(0, 'arrival'), (1, 'departure')], default=0, max_length=1),
        ),
        migrations.DeleteModel(
            name='ActivityTypeDefs',
        ),
    ]
