# Generated by Django 3.0.4 on 2020-04-17 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights_app', '0003_auto_20200417_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightactivities',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FlightComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_type', models.CharField(choices=[('0', 'Gate changing'), ('1', 'Lateness'), ('2', 'Other')], default='0', max_length=1)),
                ('com_text', models.CharField(max_length=1024)),
                ('author', models.EmailField(max_length=254)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights_app.FlightActivities')),
            ],
        ),
    ]
