# Generated by Django 3.0.4 on 2020-04-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights_app', '0004_auto_20200417_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcomments',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights_app.FlightActivities'),
            preserve_default=False,
        ),
    ]
