# Generated by Django 3.0.3 on 2020-04-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights_app', '0006_auto_20200418_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcomments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
    ]
