# Generated by Django 3.0.6 on 2020-06-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='diagnosis',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='recomendations',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
