# Generated by Django 3.0.4 on 2020-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_license',
            name='ID_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver_license',
            name='date_of_issue',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
