# Generated by Django 3.0 on 2020-06-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(verbose_name='Номер этажа')),
                ('number_of_rooms', models.IntegerField(verbose_name='Количество комнат на этаже')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, choices=[('Одноместный', 'Одноместный'), ('Двухместный', 'Двухместный'), ('Трехместный', 'Трехместный')], max_length=20, verbose_name='Тип номера')),
                ('price', models.IntegerField(verbose_name='Цена проживания в сутки в рублях')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО служащего')),
            ],
            options={
                'verbose_name': 'Служащий',
                'verbose_name_plural': 'Служащие',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=4, verbose_name='Номер комнаты')),
                ('phone_number', models.CharField(max_length=6, verbose_name='Номер телефона')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Floor')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.RoomType')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО проживающего')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Серия и номер паспорта')),
                ('from_town', models.CharField(max_length=50, verbose_name='Прибыл из города')),
                ('check_in', models.DateField(verbose_name='Дата заселения')),
                ('check_out', models.DateField(verbose_name='Дата выселения')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room')),
            ],
            options={
                'verbose_name': 'Проживающий',
                'verbose_name_plural': 'Проживающие',
            },
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, verbose_name='День недели')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Floor')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Servant')),
            ],
            options={
                'verbose_name': 'График уборки',
                'verbose_name_plural': 'Графики уборки',
            },
        ),
    ]
