# Generated by Django 3.0.7 on 2020-06-27 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('firm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('date_birth', models.DateField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('status_work', models.BooleanField()),
                ('last_salary', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=50)),
                ('max_rank', models.CharField(choices=[('1', '1 разряд'), ('2', '2 разряд'), ('3', '3 разряд')], default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('date_start', models.DateField()),
                ('education', models.CharField(choices=[('1', 'Среднее общее'), ('2', 'Профессиональное'), ('3', 'Высшее (бакалавриат)'), ('4', 'Высшее (магистратура)')], default='1', max_length=1)),
                ('rank', models.CharField(choices=[('1', '1 разряд'), ('2', '2 разряд'), ('3', '3 разряд')], default='1', max_length=1)),
                ('salary', models.IntegerField()),
                ('min_exp', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_engine.Employer')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_engine.Profession')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('1', 'Среднее общее'), ('2', 'Профессиональное'), ('3', 'Высшее (бакалавриат)'), ('4', 'Высшее (магистратура)')], default='1', max_length=1)),
                ('description', models.CharField(max_length=1000)),
                ('jobseeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange_engine.JobSeeker')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_org', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_engine.Profession')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_engine.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_engine.Resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_engine.Vacancy')),
            ],
        ),
    ]
