# Generated by Django 2.2 on 2020-03-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_color', models.CharField(max_length=50)),
                ('state_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.PositiveIntegerField()),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('choice_type', models.CharField(choices=[('A', 'Bike'), ('B', 'Light Rigid'), ('C', 'Medium Rigid'), ('D', 'Heavy Rigid'), ('E', 'Heavy Combination')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Car')),
                ('driver_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.DriverLicense')),
            ],
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='owner',
            field=models.ManyToManyField(related_name='temp_owner', through='project_first_app.TemporaryOwner', to='project_first_app.Car'),
        ),
        migrations.AddField(
            model_name='car',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.CarOwner'),
        ),
    ]
