# Generated by Django 2.2 on 2020-03-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlicense',
            name='owner',
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.CarOwner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporaryowner',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Car'),
        ),
    ]
