# Generated by Django 2.2 on 2020-03-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryowner',
            name='car',
        ),
        migrations.AddField(
            model_name='temporaryowner',
            name='car_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Car', verbose_name='Car'),
            preserve_default=False,
        ),
    ]
