# Generated by Django 3.0.4 on 2020-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='driverlicense',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
        migrations.DeleteModel(
            name='AutoOwner',
        ),
        migrations.DeleteModel(
            name='DriverLicense',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
