# Generated by Django 3.0.4 on 2020-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20200321_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='vehicle',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Vehicle'),
        ),
    ]
