# Generated by Django 3.0.4 on 2020-04-05 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_person_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2020, 4, 5, 11, 21, 20, 647354)),
        ),
    ]
