# Generated by Django 3.0.8 on 2020-07-02 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientroom',
            old_name='date',
            new_name='arrival_date',
        ),
        migrations.AddField(
            model_name='clientroom',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
