# Generated by Django 3.0 on 2020-06-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_auto_20200613_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='number_of_tickets',
            field=models.IntegerField(default=0, verbose_name='Количество проданных билетов'),
            preserve_default=False,
        ),
    ]
