# Generated by Django 3.0.6 on 2020-06-30 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_enrollee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='secretary',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Secretary'),
        ),
    ]
