# Generated by Django 3.0.4 on 2020-04-17 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('year_made', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('command_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=70)),
                ('dr_class', models.CharField(choices=[('Pro', 'Professional'), ('Mid', 'Middle class'), ('Beg', 'Beginner')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Win', 'Winner'), ('Prize', 'Prize place'), ('Lost', 'Not a prize place')], max_length=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_table.Car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_table.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('drivers_num', models.IntegerField()),
                ('racer', models.ManyToManyField(through='races_table.Participation', to='races_table.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_table.Race'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст комментария')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Partners', 'About partnership'), ('Race', 'About race'), ('Other', 'Other')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races_table.Driver'),
        ),
    ]
