# Generated by Django 3.0.4 on 2020-04-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='car',
        ),
        migrations.AlterField(
            model_name='driver',
            name='command_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='experience',
            field=models.CharField(max_length=50),
        ),
    ]
