# Generated by Django 3.0.4 on 2020-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races_table', '0002_auto_20200418_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='race',
            name='drivers_num',
        ),
        migrations.RemoveField(
            model_name='race',
            name='racer',
        ),
        migrations.AddField(
            model_name='driver',
            name='races',
            field=models.ManyToManyField(blank=True, through='races_table.Participation', to='races_table.Race'),
        ),
    ]
