# Generated by Django 3.0.4 on 2020-04-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races_table', '0003_auto_20200418_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='races_table.Driver'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('Partners', 'About partnership'), ('Racing', 'About racing'), ('Other', 'Other')], max_length=10),
        ),
    ]
