# Generated by Django 3.0.4 on 2020-03-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers_license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('license_type', models.CharField(choices=[('A', 'Type_A'), ('B', 'Type_B'), ('C', 'Type_C')], max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Auto',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='gosnumber',
            new_name='gov_number',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='manufacture',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='auto',
            new_name='car',
        ),
        migrations.DeleteModel(
            name='OwnerLicense',
        ),
        migrations.AddField(
            model_name='drivers_license',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Owner'),
        ),
    ]
