# Generated by Django 3.0.6 on 2020-06-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Flat',
        ),
    ]
