# Generated by Django 3.0.4 on 2020-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_number',
            field=models.CharField(max_length=6),
        ),
    ]
