# Generated by Django 3.0.5 on 2020-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
