# Generated by Django 3.0.5 on 2020-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20200503_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
