# Generated by Django 3.0.5 on 2020-05-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_auto_20200503_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
    ]
