# Generated by Django 3.0.4 on 2020-06-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_board', '0002_auto_20200623_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='served_flight',
            field=models.ManyToManyField(blank=True, related_name='served_flight', to='flight_board.Flight', verbose_name='Обслуживаемый рейс(-ы)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='flight',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='flight_board.Flight', verbose_name='Рейс(-ы)'),
        ),
    ]
