# Generated by Django 3.0.6 on 2020-05-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20200507_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carowner',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carowner',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driverslicense',
            name='type',
            field=models.CharField(choices=[('A', 'type_A'), ('B', 'type_B'), ('C', 'type_C'), ('D', 'type_D'), ('M', 'type_M')], max_length=1),
        ),
    ]
