# Generated by Django 3.0.6 on 2020-05-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20200507_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='trademark',
            new_name='mark',
        ),
    ]
