# Generated by Django 3.0.6 on 2020-05-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_auto_20200507_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carowner',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='carowner',
            name='passport',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
