# Generated by Django 3.0.4 on 2020-05-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20200516_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostClient',
        ),
    ]
