# Generated by Django 3.0.4 on 2020-05-16 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_auto_20200516_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
