# Generated by Django 3.0.4 on 2020-05-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_auto_20200516_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ManyToManyField(to='taxi.Order', verbose_name='Заказ: ')),
            ],
        ),
        migrations.RemoveField(
            model_name='costfabric',
            name='category',
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.DeleteModel(
            name='CostClient',
        ),
        migrations.DeleteModel(
            name='CostFabric',
        ),
    ]
