# Generated by Django 3.0.4 on 2020-05-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_auto_20200517_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
    ]
