# Generated by Django 3.0.6 on 2020-05-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('workers_amount', models.IntegerField()),
                ('sides_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saled_tickets_amount', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('arrival_point', models.CharField(max_length=250)),
                ('departure_point', models.CharField(max_length=250)),
                ('is_transit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('patronymic', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=250)),
                ('work_experience', models.IntegerField()),
                ('position', models.CharField(choices=[('1', 'Captain'), ('2', 'Second pilot'), ('3', 'Navigator'), ('4', 'Steward'), ('5', 'Stewardess')], default='1', max_length=1)),
                ('is_allow', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TransitLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('landing_point', models.CharField(max_length=250)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_app.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_model', models.CharField(max_length=250)),
                ('seats_num', models.IntegerField()),
                ('plane_type', models.CharField(choices=[('1', 'Passenger'), ('2', 'Cargo')], default='1', max_length=1)),
                ('plane_speed', models.IntegerField()),
                ('is_repair', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_app.Company')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_app.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('patronymic', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=250)),
                ('work_experience', models.IntegerField()),
                ('position', models.CharField(choices=[('1', 'Captain'), ('2', 'Second pilot'), ('3', 'Navigator'), ('4', 'Steward'), ('5', 'Stewardess')], default='1', max_length=1)),
                ('passport', models.IntegerField()),
                ('is_hired', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalDeparture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_app.Company')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_app.Flight')),
            ],
        ),
    ]
