# Generated by Django 3.0.4 on 2020-04-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='car_owner',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Owner'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='type',
            field=models.CharField(blank=True, choices=[('A', 'A type'), ('B', 'B type'), ('C', 'C type'), ('D', 'D type')], max_length=2),
        ),
    ]
