# Generated by Django 3.1.2 on 2020-10-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1500)),
                ('short_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('birth', models.DateField(blank=True)),
                ('death', models.DateField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='authors')),
                ('a_slug', models.SlugField(max_length=120, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('career', models.CharField(blank=True, max_length=300)),
                ('direction', models.CharField(blank=True, max_length=300)),
                ('a_ganre', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_lang_name', models.CharField(db_index=True, max_length=120)),
                ('orig_lang', models.CharField(choices=[('aa', 'Afar'), ('ab', 'Abkhazian'), ('af', 'Afrikaans'), ('am', 'Amharic'), ('ar', 'Arabic'), ('as', 'Assamese'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('ba', 'Bashkir'), ('be', 'Byelorussian'), ('bg', 'Bulgarian'), ('bh', 'Bihari'), ('bi', 'Bislama'), ('bn', 'Bengali'), ('bo', 'Tibetan'), ('br', 'Breton'), ('ca', 'Catalan'), ('co', 'Corsican'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dz', 'Bhutani'), ('el', 'Greek'), ('en', 'English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fj', 'Fiji'), ('fo', 'Faroese'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scots Gaelic'), ('gl', 'Galician'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('iw', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('in', 'Indonesian'), ('ie', 'Interlingue'), ('ik', 'Inupiak'), ('is', 'Icelandic'), ('it', 'Italian'), ('iu', 'Inuktitut'), ('ja', 'Japanese'), ('jw', 'Javanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('kl', 'Greenlandic'), ('km', 'Cambodian'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ks', 'Kashmiri'), ('ku', 'Kurdish'), ('ky', 'Kirghiz'), ('la', 'Latin'), ('ln', 'Lingala'), ('lo', 'Laotian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('lv', 'Lettish'), ('mg', 'Malagasy'), ('mi', 'Maori'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mo', 'Moldavian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mt', 'Maltese'), ('my', 'Burmese'), ('na', 'Nauru'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('oc', 'Occitan'), ('om', 'Oromo'), ('or', 'Oriya'), ('pa', 'Pundjabi'), ('pl', 'Polish'), ('ps', 'Pashto'), ('pt', 'Portuguese'), ('qu', 'Quechua'), ('rm', 'Rhaeto-Romance'), ('rn', 'Kirundi'), ('ro', 'Romanian'), ('ru', 'Russian'), ('rw', 'Kiyarwanda'), ('sa', 'Sanskrit'), ('sd', 'Sindhi'), ('sg', 'Sangho'), ('sh', 'Serbo-Croatian'), ('si', 'Singhalese'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sm', 'Samoan'), ('sn', 'Shona'), ('so', 'Somali'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('ss', 'Siswati'), ('st', 'Sesotho'), ('su', 'Sudanese'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('ti', 'Tigrinya'), ('tk', 'Turkmen'), ('tl', 'Tagalog'), ('tn', 'Setswana'), ('to', 'Tonga'), ('tr', 'Turkish'), ('ts', 'Tsonga'), ('tt', 'Tatar'), ('tw', 'Twi'), ('ug', 'Uigur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('vo', 'Volapuk'), ('wo', 'Wolof'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('ji', 'Yiddish'), ('yo', 'Yorouba'), ('za', 'Zhuang'), ('zh', 'Chinese'), ('zu', 'Zulu')], max_length=2)),
                ('trans_lang', models.CharField(blank=True, choices=[('aa', 'Afar'), ('ab', 'Abkhazian'), ('af', 'Afrikaans'), ('am', 'Amharic'), ('ar', 'Arabic'), ('as', 'Assamese'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('ba', 'Bashkir'), ('be', 'Byelorussian'), ('bg', 'Bulgarian'), ('bh', 'Bihari'), ('bi', 'Bislama'), ('bn', 'Bengali'), ('bo', 'Tibetan'), ('br', 'Breton'), ('ca', 'Catalan'), ('co', 'Corsican'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dz', 'Bhutani'), ('el', 'Greek'), ('en', 'English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fj', 'Fiji'), ('fo', 'Faroese'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scots Gaelic'), ('gl', 'Galician'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('iw', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('in', 'Indonesian'), ('ie', 'Interlingue'), ('ik', 'Inupiak'), ('is', 'Icelandic'), ('it', 'Italian'), ('iu', 'Inuktitut'), ('ja', 'Japanese'), ('jw', 'Javanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('kl', 'Greenlandic'), ('km', 'Cambodian'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ks', 'Kashmiri'), ('ku', 'Kurdish'), ('ky', 'Kirghiz'), ('la', 'Latin'), ('ln', 'Lingala'), ('lo', 'Laotian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('lv', 'Lettish'), ('mg', 'Malagasy'), ('mi', 'Maori'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mo', 'Moldavian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mt', 'Maltese'), ('my', 'Burmese'), ('na', 'Nauru'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('oc', 'Occitan'), ('om', 'Oromo'), ('or', 'Oriya'), ('pa', 'Pundjabi'), ('pl', 'Polish'), ('ps', 'Pashto'), ('pt', 'Portuguese'), ('qu', 'Quechua'), ('rm', 'Rhaeto-Romance'), ('rn', 'Kirundi'), ('ro', 'Romanian'), ('ru', 'Russian'), ('rw', 'Kiyarwanda'), ('sa', 'Sanskrit'), ('sd', 'Sindhi'), ('sg', 'Sangho'), ('sh', 'Serbo-Croatian'), ('si', 'Singhalese'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sm', 'Samoan'), ('sn', 'Shona'), ('so', 'Somali'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('ss', 'Siswati'), ('st', 'Sesotho'), ('su', 'Sudanese'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('ti', 'Tigrinya'), ('tk', 'Turkmen'), ('tl', 'Tagalog'), ('tn', 'Setswana'), ('to', 'Tonga'), ('tr', 'Turkish'), ('ts', 'Tsonga'), ('tt', 'Tatar'), ('tw', 'Twi'), ('ug', 'Uigur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('vo', 'Volapuk'), ('wo', 'Wolof'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('ji', 'Yiddish'), ('yo', 'Yorouba'), ('za', 'Zhuang'), ('zh', 'Chinese'), ('zu', 'Zulu')], max_length=2)),
                ('editor', models.CharField(blank=True, max_length=300)),
                ('translator', models.CharField(blank=True, max_length=300)),
                ('narrator', models.CharField(blank=True, max_length=300)),
                ('illustrator', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('publication_date', models.DateField(blank=True)),
                ('type_cover', models.CharField(choices=[('NC', 'None'), ('SC', 'Soft'), ('PB', 'Paperback'), ('OC', 'Ordinary'), ('HC', 'Hard'), ('AC', 'Audio CD'), ('AB', 'Audiobook'), ('AA', 'Audible Audio'), ('EB', 'Ebook'), ('KE', 'Kindle Edition')], max_length=2)),
                ('cover', models.ImageField(blank=True, upload_to='books')),
                ('b_slug', models.SlugField()),
                ('b_ganre', models.CharField(blank=True, max_length=300)),
                ('authors', models.ManyToManyField(blank=True, to='presencing_publications.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=240)),
                ('short_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorDuties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField()),
                ('date_left', models.DateField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.director')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('full_another_name', models.CharField(blank=True, max_length=240)),
                ('parent', models.CharField(blank=True, max_length=300)),
                ('foundation_date', models.DateField(blank=True)),
                ('p_slug', models.SlugField(max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='publishers')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('fact_address', models.CharField(blank=True, max_length=240)),
                ('city', models.CharField(blank=True, max_length=180)),
                ('country', models.CharField(max_length=60)),
                ('about', models.TextField(blank=True, max_length=2000)),
                ('Director', models.ManyToManyField(blank=True, through='presencing_publications.DirectorDuties', to='presencing_publications.Director')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=139)),
                ('publication_date', models.DateField(blank=True)),
                ('type_cover', models.CharField(choices=[('N', 'None'), ('S', 'Soft'), ('H', 'Hard')], max_length=1)),
                ('mockup', models.ImageField(blank=True, upload_to='series')),
                ('s_slug', models.SlugField()),
                ('books', models.ManyToManyField(blank=True, to='presencing_publications.Book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='directorduties',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.publisher'),
        ),
    ]
