# Generated by Django 3.1.2 on 2020-10-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencing_publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='Director',
            new_name='director',
        ),
        migrations.AddField(
            model_name='publisher',
            name='distribution',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publisher',
            name='founder',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
