# Generated by Django 3.1.2 on 2020-11-02 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presencing_publications', '0007_auto_20201026_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=600, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('website', models.URLField(unique=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('shop_slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.RemoveField(
            model_name='series',
            name='s_slug',
        ),
        migrations.AddField(
            model_name='author',
            name='who_load',
            field=models.CharField(default='Admin', max_length=120),
        ),
        migrations.AddField(
            model_name='book',
            name='who_load',
            field=models.CharField(default='Admin', max_length=120),
        ),
        migrations.AddField(
            model_name='publisher',
            name='who_load',
            field=models.CharField(default='Admin', max_length=120),
        ),
        migrations.AddField(
            model_name='series',
            name='series_slug',
            field=models.SlugField(default='Admin', verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='b_ganre',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ganre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='b_slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='book',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='orig_lang',
            field=models.CharField(choices=[('aa', 'Afar'), ('ab', 'Abkhazian'), ('af', 'Afrikaans'), ('am', 'Amharic'), ('ar', 'Arabic'), ('as', 'Assamese'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('ba', 'Bashkir'), ('be', 'Byelorussian'), ('bg', 'Bulgarian'), ('bh', 'Bihari'), ('bi', 'Bislama'), ('bn', 'Bengali'), ('bo', 'Tibetan'), ('br', 'Breton'), ('ca', 'Catalan'), ('co', 'Corsican'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dz', 'Bhutani'), ('el', 'Greek'), ('en', 'English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fj', 'Fiji'), ('fo', 'Faroese'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scots Gaelic'), ('gl', 'Galician'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('iw', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('in', 'Indonesian'), ('ie', 'Interlingue'), ('ik', 'Inupiak'), ('is', 'Icelandic'), ('it', 'Italian'), ('iu', 'Inuktitut'), ('ja', 'Japanese'), ('jw', 'Javanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('kl', 'Greenlandic'), ('km', 'Cambodian'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ks', 'Kashmiri'), ('ku', 'Kurdish'), ('ky', 'Kirghiz'), ('la', 'Latin'), ('ln', 'Lingala'), ('lo', 'Laotian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('lv', 'Lettish'), ('mg', 'Malagasy'), ('mi', 'Maori'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mo', 'Moldavian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mt', 'Maltese'), ('my', 'Burmese'), ('na', 'Nauru'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('oc', 'Occitan'), ('om', 'Oromo'), ('or', 'Oriya'), ('pa', 'Pundjabi'), ('pl', 'Polish'), ('ps', 'Pashto'), ('pt', 'Portuguese'), ('qu', 'Quechua'), ('rm', 'Rhaeto-Romance'), ('rn', 'Kirundi'), ('ro', 'Romanian'), ('ru', 'Russian'), ('rw', 'Kiyarwanda'), ('sa', 'Sanskrit'), ('sd', 'Sindhi'), ('sg', 'Sangho'), ('sh', 'Serbo-Croatian'), ('si', 'Singhalese'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sm', 'Samoan'), ('sn', 'Shona'), ('so', 'Somali'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('ss', 'Siswati'), ('st', 'Sesotho'), ('su', 'Sudanese'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('ti', 'Tigrinya'), ('tk', 'Turkmen'), ('tl', 'Tagalog'), ('tn', 'Setswana'), ('to', 'Tonga'), ('tr', 'Turkish'), ('ts', 'Tsonga'), ('tt', 'Tatar'), ('tw', 'Twi'), ('ug', 'Uigur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('vo', 'Volapuk'), ('wo', 'Wolof'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('ji', 'Yiddish'), ('yo', 'Yorouba'), ('za', 'Zhuang'), ('zh', 'Chinese'), ('zu', 'Zulu')], max_length=2, verbose_name='Original language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='orig_lang_title',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Original language title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='trans_lang',
            field=models.CharField(blank=True, choices=[('aa', 'Afar'), ('ab', 'Abkhazian'), ('af', 'Afrikaans'), ('am', 'Amharic'), ('ar', 'Arabic'), ('as', 'Assamese'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('ba', 'Bashkir'), ('be', 'Byelorussian'), ('bg', 'Bulgarian'), ('bh', 'Bihari'), ('bi', 'Bislama'), ('bn', 'Bengali'), ('bo', 'Tibetan'), ('br', 'Breton'), ('ca', 'Catalan'), ('co', 'Corsican'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dz', 'Bhutani'), ('el', 'Greek'), ('en', 'English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fj', 'Fiji'), ('fo', 'Faroese'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scots Gaelic'), ('gl', 'Galician'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('iw', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('in', 'Indonesian'), ('ie', 'Interlingue'), ('ik', 'Inupiak'), ('is', 'Icelandic'), ('it', 'Italian'), ('iu', 'Inuktitut'), ('ja', 'Japanese'), ('jw', 'Javanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('kl', 'Greenlandic'), ('km', 'Cambodian'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ks', 'Kashmiri'), ('ku', 'Kurdish'), ('ky', 'Kirghiz'), ('la', 'Latin'), ('ln', 'Lingala'), ('lo', 'Laotian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('lv', 'Lettish'), ('mg', 'Malagasy'), ('mi', 'Maori'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mo', 'Moldavian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mt', 'Maltese'), ('my', 'Burmese'), ('na', 'Nauru'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('oc', 'Occitan'), ('om', 'Oromo'), ('or', 'Oriya'), ('pa', 'Pundjabi'), ('pl', 'Polish'), ('ps', 'Pashto'), ('pt', 'Portuguese'), ('qu', 'Quechua'), ('rm', 'Rhaeto-Romance'), ('rn', 'Kirundi'), ('ro', 'Romanian'), ('ru', 'Russian'), ('rw', 'Kiyarwanda'), ('sa', 'Sanskrit'), ('sd', 'Sindhi'), ('sg', 'Sangho'), ('sh', 'Serbo-Croatian'), ('si', 'Singhalese'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sm', 'Samoan'), ('sn', 'Shona'), ('so', 'Somali'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('ss', 'Siswati'), ('st', 'Sesotho'), ('su', 'Sudanese'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('ti', 'Tigrinya'), ('tk', 'Turkmen'), ('tl', 'Tagalog'), ('tn', 'Setswana'), ('to', 'Tonga'), ('tr', 'Turkish'), ('ts', 'Tsonga'), ('tt', 'Tatar'), ('tw', 'Twi'), ('ug', 'Uigur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('vo', 'Volapuk'), ('wo', 'Wolof'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('ji', 'Yiddish'), ('yo', 'Yorouba'), ('za', 'Zhuang'), ('zh', 'Chinese'), ('zu', 'Zulu')], max_length=2, null=True, verbose_name='Translation language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type_cover',
            field=models.CharField(blank=True, choices=[('NC', 'None cover'), ('SC', 'Soft cover'), ('PB', 'Paperback'), ('OC', 'Ordinary'), ('HC', 'Hard cover'), ('AC', 'Audio CD'), ('AB', 'Audiobook'), ('AA', 'Audible Audio'), ('EB', 'Ebook'), ('KE', 'Kindle Edition')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='type_cover',
            field=models.CharField(blank=True, choices=[('NC', 'None cover'), ('SC', 'Soft cover'), ('PB', 'Paperback'), ('OC', 'Ordinary'), ('HC', 'Hard cover'), ('AC', 'Audio CD'), ('AB', 'Audiobook'), ('AA', 'Audible Audio'), ('EB', 'Ebook'), ('KE', 'Kindle Edition')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('type_user', models.CharField(blank=True, choices=[('A', 'Author'), ('M', 'Admin'), ('P', 'Publisher'), ('S', 'Book Shop'), ('U', 'User')], max_length=2, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users')),
                ('uniq_num', models.IntegerField(blank=True, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('nationality', models.CharField(max_length=300)),
                ('isu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.book')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('shelf_slug', models.SlugField(verbose_name='Slug')),
                ('books', models.ManyToManyField(blank=True, null=True, to='presencing_publications.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('A', 'Author'), ('B', 'Book'), ('P', 'Publisher'), ('S', 'Shop')], max_length=2, null=True)),
                ('importance', models.CharField(blank=True, choices=[('UI', 'Urgent and important'), ('NI', 'Not urgent and important'), ('NN', 'Not urgent and not important'), ('IB', 'I am bored')], max_length=2, null=True, verbose_name='Importance')),
                ('content', models.CharField(max_length=600)),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('place_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.author')),
                ('place_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.book')),
                ('place_publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.publisher')),
                ('place_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presencing_publications.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Commentator')),
            ],
        ),
    ]
