# Generated by Django 3.1.2 on 2020-11-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencing_publications', '0008_auto_20201102_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='short_name',
            field=models.CharField(max_length=200),
        ),
    ]
