# Generated by Django 3.1.2 on 2020-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencing_publications', '0009_auto_20201103_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type_cover',
            field=models.CharField(blank=True, choices=[('NC', 'None cover (NC)'), ('SC', 'Soft cover (SC)'), ('PB', 'Paperback (PB)'), ('OC', 'Ordinary (OC)'), ('HC', 'Hard cover (HC)'), ('AC', 'Audio CD (AC)'), ('AB', 'Audiobook (AB)'), ('AA', 'Audible Audio (AA)'), ('EB', 'Ebook (EB)'), ('KE', 'Kindle Edition (KE)')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='type_cover',
            field=models.CharField(blank=True, choices=[('NC', 'None cover (NC)'), ('SC', 'Soft cover (SC)'), ('PB', 'Paperback (PB)'), ('OC', 'Ordinary (OC)'), ('HC', 'Hard cover (HC)'), ('AC', 'Audio CD (AC)'), ('AB', 'Audiobook (AB)'), ('AA', 'Audible Audio (AA)'), ('EB', 'Ebook (EB)'), ('KE', 'Kindle Edition (KE)')], max_length=2, null=True),
        ),
    ]
