# Generated by Django 3.1.2 on 2020-11-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencing_publications', '0010_auto_20201103_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='presencing_publications.Author'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='director',
            field=models.ManyToManyField(through='presencing_publications.DirectorDuties', to='presencing_publications.Director'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='p_slug',
            field=models.SlugField(max_length=120, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(to='presencing_publications.Book'),
        ),
    ]
