# Generated by Django 3.0.7 on 2020-06-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20200624_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='car',
            field=models.ManyToManyField(through='project_first_app.Owning', to='project_first_app.Car'),
        ),
        migrations.AddField(
            model_name='passport',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
