# Generated by Django 3.0.4 on 2020-07-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(null=True, verbose_name='ФИО'),
        ),
    ]
