# Generated by Django 3.0.5 on 2020-04-17 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gate',
            options={'verbose_name': 'Гейт', 'verbose_name_plural': 'Гейты'},
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 16, 49, 2, 716056)),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 16, 49, 2, 716032)),
        ),
    ]
