# Generated by Django 3.0.5 on 2020-04-17 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flightsapp', '0002_auto_20200417_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 16, 53, 15, 415780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 16, 53, 15, 415757, tzinfo=utc)),
        ),
    ]
