# Generated by Django 3.0.5 on 2020-04-17 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flightsapp', '0003_auto_20200417_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
