# Generated by Django 3.0.5 on 2020-04-18 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flightsapp', '0007_comments_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Прилёт'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightsapp.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Отлёт'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightsapp.Direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flightnum',
            field=models.CharField(max_length=7, verbose_name='Рейс'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flighttype',
            field=models.CharField(choices=[('D', 'отлёт'), ('A', 'прилёт')], max_length=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='gate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightsapp.Gate', verbose_name='Гейт'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
