# Generated by Django 3.0 on 2020-06-12 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirCarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название авиакомпании')),
                ('country', models.CharField(max_length=50, verbose_name='Страна, которой принадлежит авиакомпания')),
                ('founded_in', models.DateField(verbose_name='Год основания авиакомпании')),
            ],
            options={
                'verbose_name': 'Авиаперевозчик',
                'verbose_name_plural': 'Авиаперевозчики',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.AirCarrier')),
            ],
            options={
                'verbose_name': 'Экипаж',
                'verbose_name_plural': 'Экипажи',
            },
        ),
        migrations.CreateModel(
            name='CrewCommander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('work_experience', models.IntegerField(verbose_name='Опыт работы в годах')),
                ('flight_admission', models.BooleanField(verbose_name='Допуск на рейс')),
            ],
            options={
                'verbose_name': 'Командир экипажа',
                'verbose_name_plural': 'Командиры экипажа',
            },
        ),
        migrations.CreateModel(
            name='Navigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('work_experience', models.IntegerField(verbose_name='Опыт работы в годах')),
                ('flight_admission', models.BooleanField(verbose_name='Допуск на рейс')),
            ],
            options={
                'verbose_name': 'Штурман',
                'verbose_name_plural': 'Штурманы',
            },
        ),
        migrations.CreateModel(
            name='SecondPilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('work_experience', models.IntegerField(verbose_name='Опыт работы в годах')),
                ('flight_admission', models.BooleanField(verbose_name='Допуск на рейс')),
            ],
            options={
                'verbose_name': 'Второй пилот',
                'verbose_name_plural': 'Вторые пилоты',
            },
        ),
        migrations.CreateModel(
            name='Steward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('work_experience', models.IntegerField(verbose_name='Опыт работы в годах')),
                ('flight_admission', models.BooleanField(verbose_name='Допуск на рейс')),
            ],
            options={
                'verbose_name': 'Бортпроводник',
                'verbose_name_plural': 'Бортпроводники',
            },
        ),
        migrations.CreateModel(
            name='TransitLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing', models.CharField(max_length=100, verbose_name='Место посадки')),
                ('date_time_landing', models.DateTimeField(verbose_name='Дата и время посадки')),
                ('date_time_takeoff', models.DateTimeField(verbose_name='Дата и время вылета')),
            ],
            options={
                'verbose_name': 'Транзитная посадка',
                'verbose_name_plural': 'Транзитные посадки',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер маршрута')),
                ('distance', models.IntegerField(verbose_name='Расстояние в км')),
                ('departure_from', models.CharField(max_length=100, verbose_name='Место вылета')),
                ('departure_time', models.DateTimeField(verbose_name='Дата и время вылета')),
                ('arrival_to', models.CharField(max_length=100, verbose_name='Место прилета')),
                ('arrival_time', models.DateTimeField(verbose_name='Дата и время прилета')),
                ('transit_landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.TransitLanding')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер самолета')),
                ('type', models.CharField(blank=True, choices=[('Ту-204', 'Ту-204'), ('Superjet-100', 'Superjet-100'), ('Airbus-A310', 'Airbus-A310'), ('Boeing-747', 'Boeing-747')], max_length=100, verbose_name='Тип кабинета')),
                ('number_of_seats', models.IntegerField(verbose_name='Количество сидений')),
                ('speed', models.IntegerField(verbose_name='Скорость самолета км/ч')),
                ('on_repairing', models.BooleanField(verbose_name='Находится на ремонте')),
                ('air_carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.AirCarrier')),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер рейса')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Crew')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Plane')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Route')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.AddField(
            model_name='crew',
            name='crew_commander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.CrewCommander'),
        ),
        migrations.AddField(
            model_name='crew',
            name='navigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Navigator'),
        ),
        migrations.AddField(
            model_name='crew',
            name='second_pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.SecondPilot'),
        ),
        migrations.AddField(
            model_name='crew',
            name='stewards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Steward'),
        ),
    ]
