# Generated by Django 3.0 on 2020-06-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='type',
            field=models.CharField(blank=True, choices=[('Ту-204', 'Ту-204'), ('Superjet-100', 'Superjet-100'), ('Airbus-A310', 'Airbus-A310'), ('Boeing-747', 'Boeing-747')], max_length=100, verbose_name='Тип самолета'),
        ),
    ]
