# Generated by Django 3.0.5 on 2020-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0003_auto_20200418_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
