# Generated by Django 3.0.5 on 2020-04-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0004_auto_20200419_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
    ]
