version: '3.7'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: airport_db_final
      POSTGRES_HOST: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    entrypoint: /bin/sh -c
    command: ["python /app/manage.py makemigrations; python /app/manage.py migrate; python /app/manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm run serve
    volumes:
    - ./frontend:/app
    - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
volumes:
  postgres_data:
  node_modules:
