# Generated by Django 3.0 on 2020-10-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('work_experience', models.IntegerField(verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('author', models.CharField(max_length=300, verbose_name='Автор курса')),
                ('lasting', models.IntegerField(verbose_name='Продолжительность')),
                ('rank', models.CharField(max_length=300, verbose_name='Разряд')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('contact', models.CharField(max_length=300, verbose_name='Контактное лицо')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(verbose_name='Контактный телефон')),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сфера деятельности',
                'verbose_name_plural': 'Сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Открыта', 'Открыта'), ('Закрыта', 'Закрыта')], max_length=20, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата регистрации вакансии')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('type', models.CharField(blank=True, choices=[('Стажировка', 'Стажировка'), ('Постоянная', 'Постоянная'), ('Временная', 'Временная'), ('Сезонная', 'Сезонная'), ('Дистанционная', 'Дистанционная')], max_length=20, verbose_name='Характер работы')),
                ('work_experience', models.IntegerField(verbose_name='Опыт работы')),
                ('rank', models.CharField(max_length=300, verbose_name='Разряд')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Education')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('rank', models.CharField(max_length=300, verbose_name='Разряд')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Applicant')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Field')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Profession')),
            ],
            options={
                'verbose_name': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Gratuity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='Размер последней зарплаты')),
                ('date_start', models.DateField(verbose_name='Дата начала выплаты')),
                ('date_end', models.DateField(verbose_name='Дата окончания выплаты')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Applicant')),
            ],
            options={
                'verbose_name': 'Пособие',
                'verbose_name_plural': 'Пособия',
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Applicant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Course')),
            ],
            options={
                'verbose_name': 'Сертификат курса',
                'verbose_name_plural': 'Сертификаты курсов',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Profession'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Одобрена', 'Одобрена'), ('В_процесе', 'В Процесе'), ('Отклонена', 'Отклонена')], max_length=20, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата подачи')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Employer')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Vacancy')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Education'),
        ),
    ]
