# Generated by Django 3.0 on 2020-10-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='field',
        ),
        migrations.AddField(
            model_name='profession',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Field'),
            preserve_default=False,
        ),
    ]
