# Generated by Django 3.0 on 2020-10-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor_exchange', '0009_auto_20201006_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='labor_exchange.Resume'),
        ),
    ]
