# Generated by Django 3.0.5 on 2020-04-16 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='task',
        ),
    ]
