# Generated by Django 3.0.5 on 2020-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrapp', '0002_remove_homework_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='homework',
            new_name='task',
        ),
        migrations.AddField(
            model_name='homework',
            name='task',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
