# Generated by Django 3.0.7 on 2020-06-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='kind',
            field=models.CharField(choices=[('Выход на посадку', 'Изменение выхода на посадку'), ('Что-то не то с рейсом', 'Проблемы с рейсом'), ('Потеряшка', 'Потерявшийся пассажир')], max_length=25),
        ),
    ]
