# Generated by Django 3.1.1 on 2020-10-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=240)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('death', models.DateField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=120)),
                ('publishDate', models.DateField()),
                ('mark', models.FloatField()),
                ('typeCover', models.CharField(choices=[('N', 'None'), ('S', 'Soft'), ('H', 'Hard')], max_length=1)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=121)),
                ('founder', models.CharField(max_length=240)),
                ('currDirector', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('books', models.ManyToManyField(to='project_first_app.Book', verbose_name='list of books')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.publisher'),
        ),
    ]
