# Generated by Django 3.0.5 on 2020-04-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('group', models.CharField(max_length=5, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Hometask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Дисциплина')),
                ('date_given', models.DateField(verbose_name='Дата выдачи задания')),
                ('deadline', models.DateField(verbose_name='Срок выполнения задания')),
                ('task_name', models.CharField(max_length=100, verbose_name='Задание')),
                ('text_of_task', models.CharField(max_length=5000, verbose_name='Описание задания')),
                ('about_fines', models.CharField(max_length=5000, verbose_name='О штрафах')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hometask.Teacher')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_comment', models.CharField(blank=True, choices=[('Вопрос_по_заданию', 'Вопрос По Заданию'), ('Найденная_ошибка', 'Найденная Ошибка'), ('Иное', 'Иное')], max_length=50, verbose_name='Тип комментария')),
                ('importance_of_comment', models.CharField(blank=True, choices=[('Срочно_и_важно', 'Срочно И Важно'), ('Не_срочно_и_важно', 'Не Срочно И Важно'), ('Не_очень_срочно_и_не_очень_важно', 'Не Очень Срочно И Не Очень Важно'), ('Я_написал_этот_комментарий_потому_что_мне_скучно', 'Я Написал Этот Комментарий Потому Что Мне Скучно')], max_length=100, verbose_name='Важность комментария')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст комментария')),
                ('hometask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hometask.Hometask')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hometask.Student')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
