# Generated by Django 3.0.5 on 2020-04-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0004_auto_20200411_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата написания'),
        ),
    ]
