# Generated by Django 3.0.5 on 2020-04-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0005_auto_20200411_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
