# Generated by Django 3.0.5 on 2020-04-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0006_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_comment', models.CharField(blank=True, choices=[('Вопрос_по_заданию', 'Вопрос По Заданию'), ('Найденная_ошибка', 'Найденная Ошибка'), ('Иное', 'Иное')], max_length=50, verbose_name='Тип комментария')),
                ('importance_of_comment', models.CharField(blank=True, choices=[('Срочно_и_важно', 'Срочно И Важно'), ('Не_срочно_и_важно', 'Не Срочно И Важно'), ('Не_очень_срочно_и_не_очень_важно', 'Не Очень Срочно И Не Очень Важно'), ('Я_написал_этот_комментарий_потому_что_мне_скучно', 'Я Написал Этот Комментарий Потому Что Мне Скучно')], max_length=100, verbose_name='Важность комментария')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст комментария')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('hometask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hometask.Hometask', verbose_name='Домашнее задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hometask.UserProfile', verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
