# Generated by Django 3.0.5 on 2020-05-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'ФИО',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=100, verbose_name='Название предемета')),
                ('homework_text', models.TextField(verbose_name='Текст задания')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deadline', models.DateTimeField(auto_now_add=True, verbose_name='Дэдлайн')),
                ('keywords', models.CharField(max_length=50, verbose_name='Ключевые слова')),
                ('teacher_fio', models.CharField(max_length=60)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shadule.Teacher', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задания',
                'verbose_name_plural': 'Задание',
            },
        ),
    ]
