# Generated by Django 3.0.5 on 2020-05-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadule', '0002_auto_20200526_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(verbose_name='Дэдлайн'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='keywords',
            field=models.CharField(max_length=50, verbose_name='Штраф за позднюю сдачу'),
        ),
    ]
