# Generated by Django 3.0.5 on 2020-05-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadule', '0004_auto_20200527_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='type',
            field=models.TextField(max_length=50, verbose_name='Тип комментария'),
        ),
    ]
