# Generated by Django 3.0.5 on 2020-05-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadule', '0005_auto_20200527_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_short',
            field=models.TextField(default='default_title', verbose_name='Задание кратко'),
        ),
    ]
