# Generated by Django 3.0 on 2020-05-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_pupil_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupils', to='school.Klass'),
        ),
    ]
