# Generated by Django 3.0.6 on 2020-05-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('passport', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_type', models.CharField(choices=[('1', 'Cargo'), ('2', 'Passenger')], default='1', max_length=1)),
                ('seats_amonut', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_point', models.CharField(max_length=50)),
                ('to_point', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransitPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(choices=[('1', 'Arrival'), ('2', 'Departure')], default='1', max_length=1)),
                ('point', models.CharField(max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('state', models.CharField(choices=[('1', 'Saled'), ('2', 'Left')], default='1', max_length=1)),
                ('price', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Flights')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'In work'), ('2', 'Under repair')], default='1', max_length=1)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Plane')),
            ],
        ),
        migrations.CreateModel(
            name='FlightTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epmloyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Employees')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Flights')),
            ],
        ),
        migrations.AddField(
            model_name='flights',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Plane'),
        ),
        migrations.AddField(
            model_name='flights',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Route'),
        ),
        migrations.CreateModel(
            name='EmloyeeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'Allow'), ('2', 'Deny')], default='1', max_length=1)),
                ('purpose', models.CharField(max_length=50)),
                ('epmloyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Challengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('passport', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('1', 'Received'), ('2', 'Rejection')], default='2', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.Company')),
            ],
        ),
    ]
