# Generated by Django 3.0.7 on 2020-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20200609_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shedule',
            old_name='group_number',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='group_number',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название предмета'),
        ),
    ]
