# Generated by Django 3.0.7 on 2020-06-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20200609_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10, verbose_name='Номер группы')),
            ],
        ),
        migrations.AlterField(
            model_name='shedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Group', verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Group', verbose_name='Номер группы'),
        ),
    ]
