# Generated by Django 3.0.7 on 2020-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20200609_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='class_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер кабинета'),
        ),
    ]
