# Generated by Django 3.0.7 on 2020-06-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20200609_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
