# Generated by Django 3.0.7 on 2020-06-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20200620_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_number', to='program.Group', verbose_name='Номер группы'),
        ),
    ]
