# Generated by Django 3.1.2 on 2020-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogshowapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='dog_class',
            field=models.CharField(max_length=20, verbose_name='Классность'),
        ),
    ]
