# Generated by Django 3.0.4 on 2020-05-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('address', models.TextField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='CostClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя категории')),
                ('cost', models.IntegerField(verbose_name='Цена сдачи мусора на переработку')),
                ('category', models.ManyToManyField(to='taxi.Category')),
            ],
            options={
                'verbose_name': 'Цена для клиента',
                'verbose_name_plural': 'Цены для клиента',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('car_model', models.CharField(max_length=30, verbose_name='Модель и марка машины')),
                ('car_number', models.CharField(max_length=10, verbose_name='Номер машины')),
                ('image', models.ImageField(upload_to='drivers/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(verbose_name='Масса мусора в кг')),
                ('complete', models.BooleanField(default=True, verbose_name='Исполнен')),
                ('data', models.DateTimeField(verbose_name='Время и дата')),
                ('category', models.ManyToManyField(to='taxi.Category', verbose_name='Мусор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Client', verbose_name='Клиент')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.CostClient', verbose_name='Цена')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='CostFabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена сдачи мусора на переработку заводу')),
                ('name', models.CharField(max_length=20, verbose_name='Имя категории')),
                ('category', models.ManyToManyField(to='taxi.Category')),
            ],
            options={
                'verbose_name': 'Цена для завода',
                'verbose_name_plural': 'Цены для завода',
            },
        ),
    ]
