# Generated by Django 3.0.4 on 2020-05-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0009_auto_20200517_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Склад'},
        ),
    ]
