# Generated by Django 3.0.4 on 2020-05-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0011_auto_20200520_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='order',
        ),
        migrations.AddField(
            model_name='storage',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxi.Order'),
            preserve_default=False,
        ),
    ]
