# Generated by Django 3.0.7 on 2020-06-22 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='название')),
                ('place', models.TextField(max_length=100, verbose_name='место')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Школа'), (2, 'Колледж')], default=1)),
            ],
            options={
                'verbose_name': 'место обучения',
                'verbose_name_plural': 'места обучения',
            },
        ),
        migrations.CreateModel(
            name='Study_Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='название')),
                ('count', models.IntegerField(verbose_name='количество студентов')),
            ],
            options={
                'verbose_name': 'программа обучения',
                'verbose_name_plural': 'программы обучения',
            },
        ),
        migrations.CreateModel(
            name='Abiturient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(max_length=100, verbose_name='фамилия')),
                ('name', models.TextField(max_length=100, verbose_name='имя')),
                ('secondname', models.TextField(max_length=100, verbose_name='отчество')),
                ('document_type', models.PositiveSmallIntegerField(choices=[(1, 'Паспорт'), (2, 'Свидетельство о рождении')], default=1, verbose_name='тип документа')),
                ('document_number', models.TextField(max_length=100, verbose_name='номер документа')),
                ('study_date', models.DateField(verbose_name='дата окончания')),
                ('award_type', models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'Серебрянная медаль'), (3, 'Золотая медаль')], default=1, verbose_name='награда')),
                ('study_type', models.PositiveSmallIntegerField(choices=[(1, 'очная'), (2, 'очно-заочная'), (3, 'заочная')], default=1, verbose_name='формат обучения')),
                ('contract_type', models.PositiveSmallIntegerField(choices=[(1, 'бюджет'), (2, 'платный')], default=1, verbose_name='тип обучения')),
                ('student_type', models.PositiveSmallIntegerField(choices=[(1, 'нет'), (2, 'целевик'), (3, 'инвалид'), (4, 'сирота')], default=1, verbose_name='тип студента')),
                ('marks', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False, verbose_name='зачислен')),
                ('study_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abit.Study_Place', verbose_name='место учебы')),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abit.Study_Program', verbose_name='программа обучения')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
            },
        ),
    ]
