# Generated by Django 3.0.4 on 2020-05-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('city', models.CharField(max_length=20, verbose_name='Из города')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_num', models.IntegerField(verbose_name='Номер этажа')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='Номер комнаты')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('price', models.IntegerField(verbose_name='Стоимость за сутки')),
                ('type', models.IntegerField(choices=[('one-room', 1), ('two-room', 2), ('three-room', 3)])),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thur'), ('Friday', 'Fr'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=20)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Floor', verbose_name='Этаж')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Уборка',
                'verbose_name_plural': 'Уборки',
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(verbose_name='Дата заселения')),
                ('date_out', models.DateField(verbose_name='Дата выезда')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Client', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room', verbose_name='Номер комнаты')),
            ],
            options={
                'verbose_name': 'Заселение',
                'verbose_name_plural': 'Заселения',
            },
        ),
    ]
