# Generated by Django 3.0.4 on 2020-05-31 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200523_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='hotel.Room', verbose_name='Номер комнаты'),
        ),
    ]
