# Generated by Django 3.0.10 on 2020-10-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200531_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='client',
            field=models.ManyToManyField(through='hotel.Checkin', to='hotel.Client'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='hotel.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='day_of_week',
            field=models.CharField(choices=[('Пон', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.Floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('1-комн', 'Однокомнатный'), ('2-комн', 'Двухкомнатный'), ('3-комн', 'Трехкомнатный')], max_length=20),
        ),
    ]
