# Generated by Django 3.0.7 on 2020-06-12 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('minimal_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VacantPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('state', models.CharField(choices=[('1', 'Осталось'), ('2', 'Подано')], default='1', max_length=1)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_comission_app.Spec')),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=1000)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_comission_app.Faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('1', 9), ('2', 11)], default='1', max_length=1)),
                ('privelege_type', models.CharField(choices=[('1', 'Нет привелегий'), ('2', 'Сирота'), ('3', 'Инвалид')], default='1', max_length=1)),
                ('fullname', models.CharField(max_length=1000)),
                ('exam_common', models.IntegerField()),
                ('exam_profile', models.IntegerField()),
                ('certificate_average', models.FloatField()),
                ('certificate', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_comission_app.Department')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_comission_app.Spec')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_comission_app.Faculty'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('state', models.CharField(choices=[('1', 'В процессе'), ('2', 'Не принято'), ('3', 'Принято')], default='1', max_length=1)),
                ('enrollee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_comission_app.Enrollee')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_comission_app.Secretary')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_comission_app.Spec')),
            ],
        ),
    ]
