# Generated by Django 3.1.2 on 2020-10-13 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('time_for_doing', models.DurationField()),
                ('task_text', models.TextField()),
                ('fine_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('type', models.CharField(choices=[('вопрос', 'вопрос'), ('найдена ошибка', 'найдена ошибка'), ('иное', 'иное')], max_length=14, verbose_name='Тип')),
                ('importance', models.CharField(choices=[('высочайшая', 'высочайшая'), ('высокая', 'высокая'), ('средняя', 'средняя'), ('низкая', 'низкая')], max_length=10, verbose_name='Важность')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zimarinapp.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
