# Generated by Django 3.0.3 on 2020-06-02 00:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0002_climbing_climbing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='climbing',
            old_name='climbing_date',
            new_name='climbing_date_end',
        ),
        migrations.AddField(
            model_name='climbing',
            name='climbing_date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climbing',
            name='status',
            field=models.CharField(choices=[('1', 'Запланировано'), ('2', 'В процессе'), ('3', 'Завершено')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='mountain',
            name='is_climbed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClubOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climber_app.Club')),
            ],
        ),
    ]
