# Generated by Django 3.0.3 on 2020-06-03 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0003_auto_20200602_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='climber',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
