# Generated by Django 3.0 on 2020-10-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor_exchange', '0002_auto_20201006_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='inn',
            field=models.CharField(max_length=10, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Контактный телефон'),
        ),
    ]
