# Generated by Django 3.0 on 2020-10-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor_exchange', '0004_auto_20201006_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labor_exchange.Profession'),
            preserve_default=False,
        ),
    ]
