# Generated by Django 3.0 on 2020-10-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor_exchange', '0006_remove_application_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
