# Generated by Django 3.1.2 on 2020-11-01 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('0', 'to hotel'), ('1', 'to home city')], max_length=20)),
                ('flight_duration', models.TimeField()),
                ('flight_days', models.CharField(max_length=30)),
                ('hotel_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('number_of_stars', models.CharField(choices=[('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=10)),
                ('number_of_rooms', models.IntegerField()),
                ('family_room', models.BooleanField()),
                ('plane_model', models.CharField(max_length=40)),
                ('number_of_passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('passport_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('row', models.IntegerField()),
                ('place', models.IntegerField()),
                ('date_of_departure', models.DateTimeField()),
                ('date_of_arrival', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('name_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.person')),
                ('number_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('row', models.IntegerField()),
                ('place', models.IntegerField()),
                ('date_of_departure', models.DateTimeField()),
                ('name_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('number_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, verbose_name='Comment')),
                ('registration_evaluation', models.CharField(choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9'), ('Ten', '10')], max_length=10)),
                ('flight_evaluation', models.CharField(choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9'), ('Ten', '10')], max_length=10)),
                ('personnel_assessment', models.CharField(choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9'), ('Ten', '10')], max_length=10)),
                ('category', models.CharField(max_length=40)),
                ('departure_date', models.DateField()),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted on')),
                ('name_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('number_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
    ]
