# Generated by Django 3.1.2 on 2020-11-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20201101_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='number_flight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
