# Generated by Django 3.1.2 on 2020-11-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_number_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='type',
            field=models.CharField(choices=[('to hotel', 'to hotel'), ('to home city', 'to home city')], max_length=20),
        ),
    ]
