# Generated by Django 3.1.2 on 2020-11-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20201101_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='number_flight',
            new_name='name_flight',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='number_flight',
            new_name='name_flight',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='number_flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='name_flight',
            field=models.CharField(default=215, max_length=3),
            preserve_default=False,
        ),
    ]
