# Generated by Django 3.0.4 on 2020-03-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30)),
                ('model_car', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('nomber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_holding', models.DateField()),
                ('end_holding', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newproj.Automobile')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newproj.Autoholder')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers_license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lisence_date', models.DateField()),
                ('lisense_type', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1)),
                ('lisense_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newproj.Autoholder')),
            ],
        ),
    ]
