# Generated by Django 3.0.5 on 2020-05-29 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0002_autoholder_holders'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalData',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='newproj.Autoholder')),
                ('passport_num', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
    ]
