# Generated by Django 3.0 on 2020-05-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200528_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
    ]
