# Generated by Django 3.0 on 2020-06-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200530_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='klass_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='school.Klass'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('klass_name', 'lesson', 'day')},
        ),
    ]
