# Generated by Django 3.0 on 2020-06-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200604_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='school.Teacher'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klass', to='school.Teacher'),
        ),
    ]
