# Generated by Django 3.0 on 2020-06-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20200605_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=2, unique=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupils', to='school.Klass', to_field='number'),
        ),
    ]
