# Generated by Django 3.0 on 2020-06-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attestat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(verbose_name='Средний балл аттестата')),
            ],
            options={
                'verbose_name': 'Аттестат',
                'verbose_name_plural': 'Аттестаты',
            },
        ),
        migrations.CreateModel(
            name='EGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сертификат ЕГЭ',
                'verbose_name_plural': 'Сертификаты ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='Enrollee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('school', models.CharField(max_length=100, verbose_name='Учебное заведение')),
                ('finish_school', models.DateField(verbose_name='Дата окончания учебного заведения')),
                ('medal', models.CharField(blank=True, choices=[('Золотая', 'Золотая'), ('Серебряная', 'Серебряная'), ('Отсутствует', 'Отсутствует')], max_length=100, verbose_name='Медаль')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Номер паспорта')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('privileges', models.CharField(blank=True, choices=[('Инвалид', 'Инвалид'), ('Сирота', 'Сирота'), ('Нет', 'Нет')], max_length=100, verbose_name='Льготы')),
                ('target', models.BooleanField(verbose_name='Целевой прием')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название факультета')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес деканата факультета')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название факультета')),
                ('profile', models.CharField(max_length=100, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='YearReceptionDigits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год приема')),
                ('budget', models.IntegerField(verbose_name='Количество мест на бюджет')),
                ('contract', models.IntegerField(verbose_name='Количество мест на контракт')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Specialty')),
            ],
            options={
                'verbose_name': 'Контрольные цифры приема',
                'verbose_name_plural': 'Контрольные цифры приема',
            },
        ),
        migrations.CreateModel(
            name='EgeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Дисциплина')),
                ('mark', models.IntegerField(verbose_name='Балл')),
                ('ege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.EGE')),
            ],
            options={
                'verbose_name': 'Дисциплина ЕГЭ',
                'verbose_name_plural': 'Дисциплины ЕГЭ',
            },
        ),
        migrations.AddField(
            model_name='ege',
            name='enrollee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Enrollee'),
        ),
        migrations.CreateModel(
            name='AttestatSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Дисциплина')),
                ('mark', models.IntegerField(verbose_name='Балл')),
                ('attestat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Attestat')),
            ],
            options={
                'verbose_name': 'Дисциплина ЕГЭ',
                'verbose_name_plural': 'Дисциплины ЕГЭ',
            },
        ),
        migrations.AddField(
            model_name='attestat',
            name='enrollee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Enrollee'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата регистрации заявки')),
                ('status', models.CharField(blank=True, choices=[('Зачислен', 'Зачислен'), ('В', 'В'), ('очереди', 'Очереди'), ('Не_зачислен', 'Не Зачислен')], max_length=100, verbose_name='Статус заявки')),
                ('form', models.CharField(blank=True, choices=[('Бюджет', 'Бюджет'), ('Контракт', 'Контракт')], max_length=100, verbose_name='Поступление на')),
                ('enrollee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Enrollee')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Faculty')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Specialty')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
