# Generated by Django 3.0 on 2020-06-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestat',
            name='enrollee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='college.Enrollee'),
        ),
        migrations.AlterField(
            model_name='ege',
            name='enrollee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='college.Enrollee'),
        ),
    ]
