# Generated by Django 3.0 on 2020-06-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20200619_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attestatsubject',
            options={'verbose_name': 'Дисциплина аттестата', 'verbose_name_plural': 'Дисциплины аттестата'},
        ),
        migrations.AddField(
            model_name='specialty',
            name='budget',
            field=models.IntegerField(null=True, verbose_name='Количество мест на бюджет'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='contract',
            field=models.IntegerField(null=True, verbose_name='Количество мест на контракт'),
        ),
        migrations.DeleteModel(
            name='YearReceptionDigits',
        ),
    ]
