# Generated by Django 3.0.4 on 2020-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20200311_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_license',
            name='ID_number',
            field=models.IntegerField(),
        ),
    ]
