# Generated by Django 3.0.4 on 2020-03-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20200311_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_license',
            name='ID_number',
        ),
    ]
