# Generated by Django 3.0.7 on 2020-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='Number',
            field=models.IntegerField(),
        ),
    ]
