# Generated by Django 3.0.7 on 2020-06-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_drivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_one', models.DateField()),
                ('Date_two', models.DateField()),
                ('Auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Auto_owner', to='App.Auto')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner_v', to='App.Owner')),
            ],
        ),
    ]
