# Generated by Django 3.0.7 on 2020-06-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_vlad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vlad',
            new_name='Possession',
        ),
    ]
