# Generated by Django 3.0.7 on 2020-06-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200619_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possession',
            name='Auto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Auto_o', to='App.Auto'),
        ),
    ]
