# Generated by Django 3.0.7 on 2020-06-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200619_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='Number',
            field=models.CharField(max_length=10),
        ),
    ]
