# Generated by Django 3.0.6 on 2020-06-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luchapp', '0002_auto_20200601_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=280)),
                ('image', models.CharField(blank=True, max_length=280)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luchapp.Request')),
            ],
        ),
    ]
