# Generated by Django 3.0.6 on 2020-06-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchapp', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='day_paid',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='day_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
