# Generated by Django 3.0.6 on 2020-06-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luchapp', '0006_auto_20200622_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='day_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
