# Generated by Django 3.0.7 on 2020-06-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50)),
                ('hometown', models.CharField(max_length=15)),
                ('passport', models.IntegerField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=15)),
                ('cost', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.CreateModel(
            name='Worktable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('weekday', models.CharField(max_length=10)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursovik.Worker')),
            ],
            options={
                'db_table': 'worktable',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(default='2006-06-06')),
                ('checkout', models.DateField(default='2006-06-07')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursovik.Client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursovik.Room')),
            ],
            options={
                'db_table': 'journal',
            },
        ),
    ]
