# Generated by Django 3.0.6 on 2020-06-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_auto_20200605_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, verbose_name='Услуга')),
                ('price', models.IntegerField(verbose_name='Стоимость услуги')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(default='no_email', max_length=50, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='no_phone', max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default='no_email', max_length=50, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='no_phone', max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='app_times',
            name='time_start',
            field=models.TimeField(verbose_name='Начало времени приема'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.Doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sex',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.Doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(to='hospital_app.PriceList'),
        ),
    ]
