# Generated by Django 3.0 on 2020-06-09 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AviaCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название авиакомпании')),
                ('country', models.CharField(max_length=50, verbose_name='Страна, которой принадлежит авиакомпания')),
                ('founded_in', models.DateField(verbose_name='Год основания авиакомпании')),
            ],
            options={
                'verbose_name': 'Авиакомпания',
                'verbose_name_plural': 'Авиакомпании',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, verbose_name='Номер рейса')),
                ('departure_from', models.CharField(max_length=100, verbose_name='Место вылета')),
                ('departure_time', models.DateTimeField(verbose_name='Дата и время вылета')),
                ('arrival_to', models.CharField(max_length=100, verbose_name='Место прилета')),
                ('arrival_time', models.DateTimeField(verbose_name='Дата и время прилета')),
                ('gate_number', models.CharField(max_length=10, verbose_name='Номер выхода')),
                ('aviacompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avia.AviaCompany')),
            ],
            options={
                'verbose_name': 'Полет',
                'verbose_name_plural': 'Полеты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(blank=True, choices=[('Мнформация_о_задержке', 'Мнформация О Задержке'), ('Изменение_номера_выхода', 'Изменение Номера Выхода'), ('Иное', 'Иное')], max_length=50, verbose_name='Тип комментария')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avia.Flight')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
