# Generated by Django 3.0 on 2020-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='hvhvkvk', max_length=5000, verbose_name='Текст комментария'),
            preserve_default=False,
        ),
    ]
