# Generated by Django 3.0.4 on 2020-03-22 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('colour', models.CharField(choices=[('r', 'red'), ('o', 'orange'), ('y', 'yellow'), ('g', 'green'), ('b', 'blue'), ('p', 'purple'), ('pk', 'pink'), ('r', 'red'), ('bk', 'black'), ('gy', 'grey'), ('w', 'white'), ('bn', 'brown'), ('m', 'multicolour')], max_length=2)),
                ('reg_plate', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Driver_license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('date_given', models.DateField()),
                ('type', models.CharField(choices=[('A', 'motorcycle; tricycle; quadricycle; engine capacity<50cm^2; weight<400kg'), ('A1', 'motorcycle; tricycle; weight<550kg'), ('B', 'car'), ('B1', 'tricycle; quadricycle; weight<550kg, engine capacity<50cm^2'), ('C', 'truck; weight>3500kg; trailer<750kg'), ('C1', 'truck; 3500<weight<7500kg; trailer<750kg'), ('D', 'passenger vehicle; trailer<750kg; seats>8'), ('D1', 'passenger vehicle; trailer<750kg; 8<seats<16'), ('BE', 'car with trailer'), ('CE', 'truck; weight>3500kg; trailer>750kg'), ('C1E', 'truck; trailer>750kg; truck+trailer<12000kg'), ('DE', 'passenger vehicle; trailer>750kg OR articulated bus'), ('D1E', 'bus not for passengers; trailer>750kg'), ('M', 'quadricycle; scooter; weight<350kg; engine capacity<50cm^2 '), ('Tm', 'tram'), ('Tb', 'trolleybus')], max_length=3)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owned_by',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Owner'),
        ),
    ]
