# Generated by Django 3.0.4 on 2020-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_user_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='ilivehere', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Australian', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
