# Generated by Django 3.0.4 on 2020-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(choices=[('standard', 'standard'), ('business', 'business'), ('first', 'first')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('straight', 'straight'), ('charter', 'charter'), ('transfer', 'transfer'), ('stopover', 'stopover')], max_length=10),
        ),
    ]
