# Generated by Django 3.0.5 on 2020-06-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20200610_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivinglicense',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cars',
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
    ]
