# Generated by Django 3.0.5 on 2020-06-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0010_auto_20200610_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(null=True, through='project_first_app.Ownership', to='project_first_app.Car'),
        ),
    ]
