# Generated by Django 2.1.5 on 2020-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='birth_date',
            field=models.DateField(default='default'),
        ),
    ]
