# Generated by Django 3.0.5 on 2020-06-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('time_for_doing', models.DurationField()),
                ('task_text', models.TextField()),
                ('fine_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('commenter', models.CharField(max_length=50)),
                ('comment_type', models.CharField(choices=[('question', 'question'), ('error found', 'error found'), ('else', 'else')], max_length=11)),
                ('comment_importancy', models.CharField(choices=[('highest', 'highest'), ('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=7)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_app.Homework')),
            ],
        ),
    ]
