# Generated by Django 3.0.5 on 2020-06-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0003_remove_comment_commenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Homework', 'verbose_name_plural': 'Homeworks'},
        ),
    ]
