# Generated by Django 3.0.5 on 2020-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0004_auto_20200607_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='importance',
            field=models.CharField(choices=[('highest', '0'), ('high', '1'), ('medium', '2'), ('low', '3')], max_length=7),
        ),
    ]
