# Generated by Django 3.0.5 on 2020-06-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0005_auto_20200607_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='importance',
            field=models.CharField(choices=[('высочайшая', '0'), ('высокая', '1'), ('средняя', '2'), ('низкая', '3')], max_length=10),
        ),
    ]
