# Generated by Django 3.0.5 on 2020-04-16 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Конференция')),
                ('place', models.CharField(max_length=50, verbose_name='Место проведения')),
                ('start', models.DateField(verbose_name='Начало конференции')),
                ('finish', models.DateField(verbose_name='Окончание конференции')),
                ('text_of_conference', models.CharField(max_length=5000, verbose_name='Описание конференции')),
                ('text_of_place', models.CharField(max_length=5000, verbose_name='Описание места проведения')),
                ('terms', models.CharField(max_length=5000, verbose_name='Условия участия')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_comment', models.CharField(blank=True, choices=[('Вопрос_о_возможности_участия', 'Вопрос О Возможности Участия'), ('Вопрос_о_возможности_опубликования', 'Вопрос О Возможности Опубликования'), ('Вопрос_о_месте_проведения', 'Вопрос О Месте Проведения'), ('Иное', 'Иное')], max_length=50, verbose_name='Тип комментария')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст комментария')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('conference_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1_app.Conference', verbose_name='Конференция')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
