# Generated by Django 3.0.5 on 2020-04-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='type_of_topics',
            field=models.CharField(blank=True, choices=[('Медицна', 'Медицна'), ('Спорт', 'Спорт'), ('Кино', 'Кино'), ('История', 'История'), ('Политика', 'Политика')], max_length=50, verbose_name='Тема'),
        ),
    ]
