# Generated by Django 3.0.6 on 2020-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20200526_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='diagnosis',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='recomendations',
            field=models.CharField(default='', max_length=500),
        ),
    ]
