# Generated by Django 3.0.5 on 2020-04-20 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Юзеры',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=25, verbose_name='Номер рейса')),
                ('flight_company', models.CharField(max_length=100, verbose_name='Компания')),
                ('departure', models.DateTimeField(verbose_name='Отлет')),
                ('arrival', models.DateTimeField(verbose_name='Прибытие')),
                ('flight_type', models.CharField(choices=[('arrival', 'arrival'), ('departure', 'departure')], default='arrival', max_length=20)),
                ('gate_number', models.CharField(max_length=25, verbose_name='Номер выхода')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=400, verbose_name='Категория')),
                ('text', models.CharField(max_length=400, verbose_name='Текст комментария')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Info')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
