# Generated by Django 3.0.4 on 2020-05-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_ownersmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnersModel',
        ),
    ]
