# Generated by Django 3.0.4 on 2020-05-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_delete_ownersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('birth_date', models.DateTimeField(max_length=200, verbose_name='Дата Рождения')),
            ],
            options={
                'verbose_name': 'Представление',
                'verbose_name_plural': 'Представления',
            },
        ),
    ]
