# Generated by Django 3.0.4 on 2020-05-30 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_ownersmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownersmodel',
            options={},
        ),
    ]
