# Generated by Django 3.0.4 on 2020-05-30 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0009_ownersmodel_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
