# Generated by Django 3.0.5 on 2020-04-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board', '0004_auto_20200416_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometask',
            old_name='date_given',
            new_name='assigment_date',
        ),
        migrations.RenameField(
            model_name='hometask',
            old_name='about_fines',
            new_name='fines',
        ),
        migrations.RenameField(
            model_name='hometask',
            old_name='text_of_task',
            new_name='hw_description',
        ),
        migrations.RenameField(
            model_name='hometask',
            old_name='task_name',
            new_name='hw_title',
        ),
        migrations.RenameField(
            model_name='hometask',
            old_name='deadline',
            new_name='period',
        ),
    ]
