# Generated by Django 3.0.5 on 2020-04-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board', '0007_auto_20200417_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=8000, verbose_name='Комментарий'),
        ),
    ]
