# Generated by Django 3.0.4 on 2020-05-18 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('paternity_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Editor',
            },
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Post Office',
            },
        ),
        migrations.CreateModel(
            name='PrintingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Closed', 'Closed')], max_length=7)),
            ],
            options={
                'db_table': 'Printing House',
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('edition_index', models.IntegerField()),
                ('price', models.FloatField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapersapp.Editor')),
            ],
            options={
                'db_table': 'Newspaper',
            },
        ),
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_run', models.IntegerField()),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapersapp.Newspaper')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapersapp.PostOffice')),
                ('printing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspapersapp.PrintingHouse')),
            ],
            options={
                'db_table': 'In Stock',
            },
        ),
    ]
