# Generated by Django 3.0.4 on 2020-05-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapersapp', '0002_postoffice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='paternity_name',
        ),
        migrations.AddField(
            model_name='editor',
            name='middle_name',
            field=models.CharField(default='John', max_length=40),
        ),
    ]
