# Generated by Django 2.1.3 on 2020-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181219_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('exhibition_type', models.CharField(choices=[('T1', 'Монопородная выставка'), ('T2', 'Полипородная выставка')], max_length=2)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('image', models.ImageField(upload_to='exhibition/static')),
            ],
        ),
    ]
