# Generated by Django 2.0.6 on 2020-05-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200516_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogowner',
            name='passport',
            field=models.CharField(max_length=10),
        ),
    ]
