# Generated by Django 2.1.11 on 2020-05-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dog', verbose_name='Собака')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Exhibition', verbose_name='Выставка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DogOwner', verbose_name='Хозяин')),
            ],
        ),
    ]
