# Generated by Django 2.1.11 on 2020-05-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_dogregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Competition', verbose_name='Соревнование')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dog', verbose_name='Собака')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('score3', models.IntegerField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Expert', verbose_name='Эксперт')),
            ],
        ),
        migrations.AddField(
            model_name='compparticipation',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Result', verbose_name='Результат'),
        ),
    ]
