# Generated by Django 2.1.11 on 2020-05-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200518_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compparticipation',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Result', verbose_name='Результат'),
        ),
    ]
