# Generated by Django 2.1.11 on 2020-05-19 07:46

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200518_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogregistration',
            name='dog',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='owner', chained_model_field='owner', on_delete=django.db.models.deletion.CASCADE, to='app.Dog'),
        ),
    ]
