# Generated by Django 2.1.11 on 2020-05-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200519_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dismissed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dog', verbose_name='Собака')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Exhibition', verbose_name='Выставка')),
            ],
        ),
    ]
