# Generated by Django 2.1.11 on 2020-05-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_dismissed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dismissed',
            name='exhibition',
        ),
        migrations.AddField(
            model_name='dismissed',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Exhibition', verbose_name='Соревнование'),
            preserve_default=False,
        ),
    ]
