# Generated by Django 2.1.11 on 2020-05-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200519_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dismissed',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Competition', verbose_name='Соревнование'),
        ),
    ]
