# Generated by Django 2.0.6 on 2020-05-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_exhibition_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring', models.IntegerField()),
                ('ex1', models.CharField(max_length=100)),
                ('ex2', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Exhibition', verbose_name='Ввставка')),
            ],
        ),
    ]
