# Generated by Django 2.0.6 on 2020-05-16 08:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_competition_ex3'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('passport', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Exhibition', verbose_name='Выставка'),
        ),
    ]
