# Generated by Django 2.1.11 on 2020-05-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200519_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogregistration',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dog', verbose_name='Собака'),
        ),
    ]
