# Generated by Django 2.1.11 on 2020-05-19 10:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200519_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClubParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Club', verbose_name='Клуб')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dog', verbose_name='Собака')),
            ],
        ),
        migrations.AlterField(
            model_name='dogregistration',
            name='dog',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='owner', chained_model_field='owner', on_delete=django.db.models.deletion.CASCADE, to='app.Dog', verbose_name='Собака'),
        ),
        migrations.AlterField(
            model_name='dogregistration',
            name='is_paid',
            field=models.BooleanField(verbose_name='Оплата'),
        ),
    ]
