# Generated by Django 3.0.5 on 2020-04-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20200414_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='choreographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.Choreographer'),
        ),
        migrations.AlterField(
            model_name='master',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.DanceStyle'),
        ),
    ]
