# Generated by Django 3.0.5 on 2020-04-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20200414_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={},
        ),
    ]
