# Generated by Django 3.0.5 on 2020-04-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_auto_20200414_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Хореограф-Стиль', 'verbose_name_plural': 'Хореографы и стили'},
        ),
    ]
