# Generated by Django 3.0.5 on 2020-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_auto_20200414_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='heading',
        ),
        migrations.AddField(
            model_name='workshop',
            name='heading',
            field=models.ManyToManyField(to='workshops.Master', verbose_name='Стиль + Педагог'),
        ),
    ]
