# Generated by Django 3.0.5 on 2020-04-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_auto_20200414_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='name',
            field=models.CharField(default='kkkk', max_length=100, verbose_name='Название'),
        ),
    ]
