# Generated by Django 3.0.5 on 2020-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_workshop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='type',
            field=models.CharField(choices=[('T1', 'Оплата'), ('T2', 'Дресс-код'), ('T3', 'Уровень подготовки'), ('T4', 'Другое')], default='Другое', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(default='Мастер-класс', max_length=100, verbose_name='Название'),
        ),
    ]
