# Generated by Django 3.0.5 on 2020-04-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_auto_20200415_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='type',
            field=models.CharField(choices=[('Оплата', 'Оплата'), ('Дресс-код', 'Дресс-код'), ('Уровень подготовки', 'Уровень подготовки'), ('Другое', 'Другое')], default='Оплата', max_length=20, verbose_name='Тема'),
        ),
    ]
