# Generated by Django 3.1.1 on 2020-09-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importancecomments',
            options={'verbose_name': 'Важность комментария', 'verbose_name_plural': 'Важность комментариев'},
        ),
        migrations.AlterModelOptions(
            name='typecomments',
            options={'verbose_name': 'Тип комментария', 'verbose_name_plural': 'Типы комментариев'},
        ),
    ]
