# Generated by Django 3.1.1 on 2020-09-30 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20200929_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='type',
        ),
        migrations.AddField(
            model_name='comments',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homework.typecomments', verbose_name='Тип комментария'),
            preserve_default=False,
        ),
    ]
