# Generated by Django 3.0 on 2020-06-16 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Название отеля')),
                ('address', models.CharField(max_length=5000, verbose_name='Адрес')),
                ('description', models.CharField(max_length=5000, verbose_name='Описание')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('room_types', models.CharField(max_length=5000, verbose_name='Типы номеров')),
                ('facilities', models.CharField(max_length=5000, verbose_name='Удобства')),
                ('owner', models.CharField(max_length=5000, verbose_name='Имя владельца')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50, verbose_name='Рейтинг отеля')),
                ('check_in', models.DateTimeField(verbose_name='Дата заселения')),
                ('check_out', models.DateTimeField(verbose_name='Дата выселения')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст комментария')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
