# Generated by Django 3.0 on 2020-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_comment_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='check_in',
            field=models.DateField(verbose_name='Дата заселения'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='check_out',
            field=models.DateField(verbose_name='Дата выселения'),
        ),
    ]
