# Generated by Django 3.0.6 on 2020-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
