# Generated by Django 3.0.5 on 2020-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceapp', '0003_auto_20200419_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Вопрос о сотрудничестве'), (2, 'Вопрос о гонках'), (3, 'Иное')], default=3, verbose_name='Тип комментария'),
        ),
    ]
