from django.urls import path
from . import views

urlpatterns = [
    path("crew/",views.CrewViewSet.as_view({'get': 'list'})),
    path("crew/<int:pk>/",views.CrewViewSet.as_view({'get': 'retrieve'})),
    path("crew/create",views.CrewViewSet.as_view({'post': 'create'})),
    path("crew/<int:pk>/update",views.CrewViewSet.as_view({'post': 'update'})),
    path("crew/<int:pk>/delete",views.CrewViewSet.as_view({'delete': 'destroy'})),
    path("navigator/",views.NavigatorViewSet.as_view({'get': 'list'})),
    path("navigator/<int:pk>/",views.NavigatorViewSet.as_view({'get': 'retrieve'})),
    path("navigator/create",views.NavigatorViewSet.as_view({'post': 'create'})),
    path("navigator/<int:pk>/update",views.NavigatorViewSet.as_view({'post': 'update'})),
    path("navigator/<int:pk>/delete",views.NavigatorViewSet.as_view({'delete': 'destroy'})),
    path("steward/",views.StewardViewSet.as_view({'get': 'list'})),
    path("steward/<int:pk>/",views.StewardViewSet.as_view({'get': 'retrieve'})),
    path("steward/create",views.StewardViewSet.as_view({'post': 'create'})),
    path("steward/<int:pk>/update",views.StewardViewSet.as_view({'post': 'update'})),
    path("steward/<int:pk>/delete",views.StewardViewSet.as_view({'delete': 'destroy'})),
    path("secondpilot/",views.SecondPilotViewSet.as_view({'get': 'list'})),
    path("secondpilot/<int:pk>/",views.SecondPilotViewSet.as_view({'get': 'retrieve'})),
    path("secondpilot/create",views.SecondPilotViewSet.as_view({'post': 'create'})),
    path("secondpilot/<int:pk>/update",views.SecondPilotViewSet.as_view({'post': 'update'})),
    path("secondpilot/<int:pk>/delete",views.SecondPilotViewSet.as_view({'delete': 'destroy'})),
    path("crewcommander/",views.CrewCommanderViewSet.as_view({'get': 'list'})),
    path("crewcommander/<int:pk>/",views.CrewCommanderViewSet.as_view({'get': 'retrieve'})),
    path("crewcommander/create",views.CrewCommanderViewSet.as_view({'post': 'create'})),
    path("crewcommander/<int:pk>/update",views.CrewCommanderViewSet.as_view({'post': 'update'})),
    path("crewcommander/<int:pk>/delete",views.CrewCommanderViewSet.as_view({'delete': 'destroy'})),
    path("plane/",views.PlaneViewSet.as_view({'get': 'list'})),
    path("plane/<int:pk>/",views.PlaneViewSet.as_view({'get': 'retrieve'})),
    path("plane/create",views.PlaneViewSet.as_view({'post': 'create'})),
    path("plane/<int:pk>/update",views.PlaneViewSet.as_view({'post': 'update'})),
    path("plane/<int:pk>/delete",views.PlaneViewSet.as_view({'delete': 'destroy'})),
    path("flight",views.FlightViewSet.as_view({'get': 'list'})),
    path("flight/<int:pk>/",views.FlightViewSet.as_view({'get': 'retrieve'})),
    path("aircarrier",views.AirCarrierViewSet.as_view({'get': 'list'})),
    path("aircarrier/<int:pk>/",views.AirCarrierViewSet.as_view({'get': 'retrieve'})),
    path("route/",views.RouteViewSet.as_view({'get': 'list'})),
    path("route/<int:pk>/",views.RouteViewSet.as_view({'get': 'retrieve'})),
    path("transit/",views.TransitViewSet.as_view({'get': 'list'})),
    path("transit/<int:pk>/",views.TransitViewSet.as_view({'get': 'retrieve'})),
    path('query3/', views.Query3.as_view()),
    path('query4/', views.Query4.as_view()),
    path('query5/', views.Query5.as_view()),
    path('aircarrier_reports/', views.AirCarrierReport.as_view())
]