# Generated by Django 3.0.7 on 2020-06-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner_dog',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='passport',
            name='type',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], max_length=10),
        ),
    ]
