# Generated by Django 3.0.4 on 2020-04-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_index', models.IntegerField()),
                ('country_location', models.CharField(max_length=30)),
                ('town_location', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('conference_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('country_from', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=30)),
                ('section_time', models.TimeField()),
                ('conference_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_speech', models.IntegerField()),
                ('time_of_speech', models.TimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Report')),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Scientist')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Section')),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='location_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Location'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('1', 'Participation'), ('2', 'Publication'), ('3', 'Location'), ('4', 'Other')], max_length=2)),
                ('scientist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Scientist')),
            ],
        ),
    ]
