# Generated by Django 3.0.4 on 2020-04-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='location_index',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
        migrations.AddField(
            model_name='conference',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='country_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='town_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='conference_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='conference.Conference'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
