# Generated by Django 3.0.4 on 2020-04-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20200418_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conf_comment', to='conference.Conference'),
        ),
    ]
