# Generated by Django 3.0.7 on 2020-06-29 07:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('capacity', models.IntegerField(verbose_name='Вместимость (человек)')),
                ('room_types', multiselectfield.db.fields.MultiSelectField(choices=[('single', 'A room assigned to one person'), ('double', 'A room assigned to two people'), ('triple', 'A room assigned to three people'), ('quad', 'A room assigned to four people')], max_length=25)),
                ('facilities', multiselectfield.db.fields.MultiSelectField(choices=[('restaurant', 'Restaurant'), ('parking', 'Car parking'), ('pool', 'Swimming pool'), ('internet', 'Internet'), ('fitness', 'Fitness')], max_length=40)),
                ('hotel_owner', models.CharField(max_length=100, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='hotel_images', verbose_name='Изображение')),
            ],
        ),
    ]
