# Generated by Django 3.0.7 on 2020-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200629_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(upload_to='hotel_images/', verbose_name='Изображение'),
        ),
    ]
