# Generated by Django 3.0.7 on 2020-06-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20200629_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(upload_to='hotels/static/images', verbose_name='Изображение'),
        ),
    ]
