# Generated by Django 3.0.7 on 2020-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20200630_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='Изображение'),
        ),
    ]
