# Generated by Django 3.0.7 on 2020-07-01 07:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_auto_20200630_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='room_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('single', 'single'), ('double', 'double'), ('triple', 'triple'), ('quad', 'quad')], max_length=25),
        ),
    ]
