# Generated by Django 3.0.7 on 2020-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_auto_20200701_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(upload_to='hotels_photo/', verbose_name='Изображение'),
        ),
    ]
