# Generated by Django 3.0.7 on 2020-07-03 14:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='period',
        ),
        migrations.AddField(
            model_name='comments',
            name='end_period',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата выезда'),
        ),
        migrations.AddField(
            model_name='comments',
            name='start_period',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка - от 1 до 10'),
        ),
    ]
