# Generated by Django 3.0.7 on 2020-10-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=30)),
                ('country_location', models.CharField(max_length=30, null=True)),
                ('town_location', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('conference_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('country_from', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=30)),
                ('section_time', models.TimeField()),
                ('conference_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='conference.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_speech', models.IntegerField()),
                ('time_of_speech', models.TimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Report')),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Scientist')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('body', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_type', models.CharField(choices=[('T1', 'Вопрос о возможности участия'), ('T2', 'Вопрос о возможности опубликования'), ('T3', 'Вопрос о месте проведения'), ('T4', 'Иное')], max_length=2, null=True)),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conf_com', to='conference.Conference')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
