# Generated by Django 3.0.7 on 2020-07-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0002_remove_medicalrecord_current_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TextField(max_length=100, verbose_name='Время')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicapp.Doctor', verbose_name='Доктор')),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicapp.Patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Запись',
            },
        ),
    ]
