# Generated by Django 3.0.4 on 2020-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='time_of_tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(default='15 days', max_length=100),
            preserve_default=False,
        ),
    ]
