# Generated by Django 3.0.5 on 2020-06-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nclass',
            name='letter',
            field=models.CharField(blank=True, choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=2, verbose_name='Буква'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lesson',
            field=models.CharField(blank=True, choices=[('1-8:30-9:10', '1-8:30-9:10'), ('2-9:20-10:00', '2-9:20-10:00'), ('3-10:10-10:50', '3-10:10-10:50'), ('4-11:00-11:40', '4-11:00-11:40'), ('5-12:10-12:50', '5-12:10-12:50'), ('6-13:10-13:50', '6-13:10-13:50'), ('7-14:00-14:40', '7-14:00-14:40'), ('8-14:45-15:25', '8-14:45-15:25')], max_length=50, verbose_name='Урок'),
        ),
    ]
