# Generated by Django 3.0.4 on 2020-03-21 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='end_date_of_ownership',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ownership',
            name='start_date_of_ownership',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
