# Generated by Django 3.0.4 on 2020-03-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='number',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='number',
        ),
    ]
