# Generated by Django 3.0.4 on 2020-04-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20200320_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner_dog',
        ),
        migrations.AddField(
            model_name='car',
            name='ownering',
            field=models.ManyToManyField(through='project_first_app.Owning', to='project_first_app.Owner'),
        ),
    ]
