# Generated by Django 3.0.4 on 2020-04-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_auto_20200405_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='ownering',
        ),
        migrations.AddField(
            model_name='owner',
            name='car',
            field=models.ManyToManyField(through='project_first_app.Owning', to='project_first_app.Car'),
        ),
    ]
