# Generated by Django 3.0.4 on 2020-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_auto_20200405_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
