# Generated by Django 3.0.4 on 2020-05-21 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0007_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passport',
            new_name='passsport',
        ),
        migrations.AddField(
            model_name='user',
            name='car',
            field=models.ManyToManyField(through='project_first_app.Owning', to='project_first_app.Car'),
        ),
        migrations.AlterField(
            model_name='owning',
            name='own_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passport',
            name='own_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
