# Generated by Django 3.0.4 on 2020-05-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0009_auto_20200521_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date_birth',
            field=models.DateField(default='2000.01.01'),
        ),
    ]
