# Generated by Django 3.0.4 on 2020-05-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=25)),
                ('town_club', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=25)),
                ('breed', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('date_of_medicine', models.CharField(max_length=10)),
                ('inspectation', models.CharField(choices=[('yes', 'everything is ok'), ('no', 'the dog is ill')], default='no', max_length=3)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=25)),
                ('show_town', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('1', 'one breed'), ('not1', 'a lot of breeds')], max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=25)),
                ('passport', models.CharField(max_length=25)),
                ('expert', models.CharField(choices=[('exp', 'expert'), ('part', 'participant')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('ex1', models.CharField(max_length=25)),
                ('ex2', models.CharField(max_length=25)),
                ('ex3', models.CharField(max_length=25)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('fee', models.CharField(choices=[('yes', 'fee paid'), ('no', 'not paid')], default='no', max_length=3)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.User')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Ring')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points1', models.CharField(max_length=5)),
                ('points2', models.CharField(max_length=5)),
                ('points3', models.CharField(max_length=5)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.User')),
                ('perform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Perform')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.User'),
        ),
    ]
