# Generated by Django 3.0.4 on 2020-05-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.IntegerField(null=True),
        ),
    ]
