# Generated by Django 3.0.4 on 2020-06-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_auto_20200601_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='num',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='owner',
        ),
    ]
