# Generated by Django 3.0.4 on 2020-06-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_auto_20200606_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ring',
            name='number',
        ),
    ]
