# Generated by Django 3.0.4 on 2020-05-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='passport_number',
            field=models.IntegerField(verbose_name='Номер пасспорта'),
        ),
    ]
