# Generated by Django 3.0.4 on 2020-03-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20200321_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state_number',
            field=models.CharField(max_length=10, verbose_name='Гос номер'),
        ),
    ]
