# Generated by Django 3.0.4 on 2020-05-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(default='Planet Earth', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(default='Who cares', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='passport',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='date_of_birth',
            field=models.DateField(default='1998-04-20'),
        ),
    ]
