# Generated by Django 3.0.4 on 2020-03-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslicense',
            name='category',
            field=models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D'), ('M', 'Class M'), ('ACDL', 'Class A CDL'), ('BCDL', 'Class B CDL'), ('CCDL', 'Class C CDL'), ('MCDL', 'Class M CDL')], max_length=4),
        ),
    ]
