# Generated by Django 3.0.4 on 2020-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20200321_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='6TRJ244', max_length=7),
        ),
        migrations.AddField(
            model_name='driverslicense',
            name='license_number',
            field=models.IntegerField(default=12345678),
        ),
    ]
