# Generated by Django 3.0.4 on 2020-03-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20200321_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='driverslicense',
            name='license_number',
            field=models.IntegerField(),
        ),
    ]
