# Generated by Django 3.0.4 on 2020-04-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('contacts', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('type', models.CharField(choices=[('depart', 'departure'), ('arrive', 'arrival')], max_length=15)),
                ('gate_num', models.CharField(max_length=5)),
                ('flight_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avia.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('gate', 'gate change'), ('arrival', 'arrival problems'), ('depart', 'departure problems'), ('lost', 'lost passenger')], max_length=25)),
                ('flight_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avia.Flight')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avia.Passenger')),
            ],
        ),
    ]
