# Generated by Django 3.0.4 on 2020-04-18 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='kind',
            field=models.CharField(choices=[('A1', 'Изменение gate №'), ('A2', 'Проблемы с прилетом'), ('A3', 'Проблемы с отправлением'), ('A4', 'Потерявшийся пассажир')], max_length=25),
        ),
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
