# Generated by Django 3.0.4 on 2020-04-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0002_auto_20200418_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='type',
            field=models.CharField(choices=[('up', 'отправление'), ('down', 'прибытие')], max_length=15),
        ),
    ]
