from django.urls import path
from . import views

urlpatterns = [
    path("education/", views.EducationViewSet.as_view({'get': 'list'})),
    path("education/<int:pk>/", views.EducationViewSet.as_view({'get': 'retrieve'})),
    path("education/create", views.EducationViewSet.as_view({'post': 'create'})),
    path("education/<int:pk>/delete", views.EducationViewSet.as_view({'delete': 'destroy'})),
    path("education/<int:pk>/update", views.EducationViewSet.as_view({'post': 'update'})),
    path("profession/", views.ProfessionViewSet.as_view({'get': 'list'})),
    path("profession/<int:pk>/", views.ProfessionViewSet.as_view({'get': 'retrieve'})),
    path("field/", views.FieldViewSet.as_view({'get': 'list'})),
    path("field/<int:pk>/", views.FieldViewSet.as_view({'get': 'retrieve'})),
    path("applicant/", views.ApplicantViewSet.as_view({'get': 'list'})),
    path("applicant/<int:pk>/", views.ApplicantViewSet.as_view({'get': 'retrieve'})),
    path("applicant/create", views.ApplicantViewSet.as_view({'post': 'create'})),
    path("applicant/<int:pk>/delete", views.ApplicantViewSet.as_view({'delete': 'destroy'})),
    path("applicant/<int:pk>/update", views.ApplicantViewSet.as_view({'post': 'update'})),
    path("resume/", views.ResumeViewSet.as_view({'get': 'list'})),
    path("resume/<int:pk>/", views.ResumeViewSet.as_view({'get': 'retrieve'})),
    path("resume/create", views.ResumeViewSet.as_view({'post': 'create'})),
    path("resume/<int:pk>/delete", views.ResumeViewSet.as_view({'delete': 'destroy'})),
    path("resume/<int:pk>/update", views.ResumeViewSet.as_view({'post': 'update'})),
    path("course/", views.CourseViewSet.as_view({'get': 'list'})),
    path("course/<int:pk>/", views.CourseViewSet.as_view({'get': 'retrieve'})),
    path("course/create", views.CourseViewSet.as_view({'post': 'create'})),
    path("course_certificate/", views.CourseCertificateViewSet.as_view({'get': 'list'})),
    path("course_certificate/<int:pk>/", views.CourseCertificateViewSet.as_view({'get': 'retrieve'})),
    path("course_certificate/create", views.CourseCertificateViewSet.as_view({'post': 'create'})),
    path("gratuity/", views.GratuityViewSet.as_view({'get': 'list'})),
    path("gratuity/<int:pk>/", views.GratuityViewSet.as_view({'get': 'retrieve'})),
    path("gratuity/create", views.GratuityViewSet.as_view({'post': 'create'})),
    path("gratuity/<int:pk>/delete", views.GratuityViewSet.as_view({'delete': 'destroy'})),
    path("gratuity/<int:pk>/update", views.GratuityViewSet.as_view({'post': 'update'})),
    path("employer/", views.EmployerViewSet.as_view({'get': 'list'})),
    path("employer/<int:pk>/", views.EmployerViewSet.as_view({'get': 'retrieve'})),
    path("employer/create", views.EmployerViewSet.as_view({'post': 'create'})),
    path("employer/<int:pk>/delete", views.EmployerViewSet.as_view({'delete': 'destroy'})),
    path("employer/<int:pk>/update", views.EmployerViewSet.as_view({'post': 'update'})),
    path("vacancy/", views.VacancyViewSet.as_view({'get': 'list'})),
    path("vacancy/<int:pk>/", views.VacancyViewSet.as_view({'get': 'retrieve'})),
    path("vacancy/create", views.VacancyViewSet.as_view({'post': 'create'})),
    path("vacancy/<int:pk>/delete", views.VacancyViewSet.as_view({'delete': 'destroy'})),
    path("vacancy/<int:pk>/update", views.VacancyViewSet.as_view({'post': 'update'})),
    path("application/", views.ApplicationViewSet.as_view({'get': 'list'})),
    path("application/<int:pk>/", views.ApplicationViewSet.as_view({'get': 'retrieve'})),
    path("application/create", views.ApplicationViewSet.as_view({'post': 'create'})),
    path("application/<int:pk>/delete", views.ApplicationViewSet.as_view({'delete': 'destroy'})),
    path("application/<int:pk>/update", views.ApplicationViewSet.as_view({'post': 'update'})),
    path('count_course/', views.CountCourse.as_view()),
]