# Generated by Django 3.0.4 on 2020-05-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_auto_20200516_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(verbose_name='Масса мусора в кг')),
                ('complete', models.BooleanField(default=True, verbose_name='Исполнен')),
                ('data', models.DateTimeField(verbose_name='Время и дата')),
                ('category', models.ManyToManyField(to='taxi.Category', verbose_name='Мусор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Client', verbose_name='Клиент')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.CostClient', verbose_name='Цена')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.Driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
