# Generated by Django 3.0.4 on 2020-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0013_auto_20200523_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(to='taxi.Category', verbose_name='Мусор'),
        ),
    ]
