# Generated by Django 3.1.2 on 2020-11-01 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='Название отеля')),
                ('hotel_owner', models.CharField(max_length=100, verbose_name='Владелец отеля')),
                ('hotel_address', models.CharField(max_length=500, verbose_name='Адрес отеля')),
                ('hotel_description', models.TextField(max_length=1000, verbose_name='Описание отеля')),
                ('hotel_capacity', models.IntegerField(max_length=7, verbose_name='Вместимость отеля')),
                ('hotel_class', models.CharField(max_length=50, verbose_name='Класс отеля')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('1', '1 гость'), ('2', '2 гостя'), ('3', '3 гостя'), ('4', '4 гостя'), ('6', '6 гостей')], max_length=1, verbose_name='Тип номера')),
                ('room_price', models.CharField(max_length=20, verbose_name='Цена номера')),
                ('room_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_list.hotels')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rank', models.CharField(choices=[('1', 'Очень плохо'), ('2', 'Плохо'), ('3', 'Средне'), ('4', 'Хорошо'), ('5', 'Очень хорошо')], max_length=1, verbose_name='Рейтинг отеля')),
                ('review_period', models.CharField(choices=[('SU', 'Summer'), ('AU', 'Autumn'), ('WI', 'Winter'), ('SP', 'Spring')], max_length=2, verbose_name='Период проживания')),
                ('review_text', models.TextField(max_length=500, verbose_name='Текст отзыва')),
                ('review_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('review_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_list.hotels')),
                ('review_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start', models.DateField()),
                ('reservation_end', models.DateField()),
                ('reservation_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_list.rooms')),
                ('reservation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
