# Generated by Django 3.1.2 on 2020-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_capacity',
            field=models.IntegerField(verbose_name='Вместимость отеля'),
        ),
    ]
