# Generated by Django 3.1.2 on 2020-11-01 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels_list', '0002_auto_20201101_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Reservations',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
