# Generated by Django 3.1.2 on 2020-11-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_list', '0003_auto_20201101_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name': 'Резервирование', 'verbose_name_plural': 'Резервирования'},
        ),
    ]
