# Generated by Django 3.1.2 on 2020-11-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_list', '0006_auto_20201101_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
