# Generated by Django 3.1.2 on 2020-11-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_list', '0007_auto_20201101_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_period',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=6, verbose_name='Период проживания'),
        ),
    ]
