# Generated by Django 3.1.2 on 2020-11-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_list', '0008_auto_20201101_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
