# Generated by Django 3.1.2 on 2020-11-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_list', '0009_reviews_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='moderation',
        ),
    ]
