# Generated by Django 2.1.5 on 2020-04-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_type', models.CharField(choices=[('T1', 'Вопрос о возможности участия'), ('T2', 'Вопрос о возможности опубликования'), ('T3', 'Вопрос о месте проведения'), ('T4', 'Иное')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('conference_description', models.TextField()),
                ('place_description', models.TextField()),
                ('conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference_themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_interface.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_interface.Conference'),
        ),
    ]
