# Generated by Django 2.1.5 on 2020-04-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_interface', '0003_auto_20200410_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='promo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
