# Generated by Django 2.1.5 on 2020-04-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_interface', '0005_auto_20200411_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='promo',
            field=models.ImageField(),
        ),
    ]
