# Generated by Django 2.1.5 on 2020-04-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_interface', '0006_auto_20200411_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='promo',
        ),
    ]
