# Generated by Django 2.1.5 on 2020-04-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_interface', '0007_remove_conference_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='promo',
            field=models.ImageField(default='dd', upload_to=''),
        ),
    ]
