# Generated by Django 2.1.5 on 2020-04-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_interface', '0008_conference_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_interface.User'),
            preserve_default=False,
        ),
    ]
