# Generated by Django 2.1.5 on 2020-04-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_interface', '0009_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
