# Generated by Django 2.1.5 on 2020-04-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_interface', '0012_auto_20200412_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
