# Generated by Django 2.1.5 on 2020-04-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_interface', '0015_auto_20200412_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
