# Generated by Django 2.0.6 on 2020-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='grade',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lesson_num',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
    ]
