# Generated by Django 2.0.6 on 2020-05-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200520_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subject'),
        ),
    ]
