# Generated by Django 2.0.6 on 2020-05-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20200520_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='grade',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], default=4),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='term',
            field=models.IntegerField(default=4),
        ),
    ]
