# Generated by Django 2.0.6 on 2020-05-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200527_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
    ]
