# Generated by Django 2.0.6 on 2020-05-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20200527_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='teacher',
        ),
    ]
