# Generated by Django 2.0.6 on 2020-05-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20200527_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='guiding_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
    ]
