# Generated by Django 2.0.6 on 2020-05-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20200529_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Teacher'),
        ),
    ]
