# Generated by Django 2.0.6 on 2020-05-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20200530_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='guiding_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Teacher'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='study_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Class'),
        ),
        migrations.AlterField(
            model_name='room',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Subject'),
        ),
    ]
