# Generated by Django 2.0.6 on 2020-05-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20200530_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Subject'),
        ),
    ]
