# Generated by Django 3.0.4 on 2020-05-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_ownersmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnersModel',
        ),
    ]
