# Generated by Django 3.0.5 on 2020-05-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalData',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project_first_app.Owner')),
                ('passport_num', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='members',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Auto'),
        ),
    ]
