# Generated by Django 3.0.6 on 2020-06-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_avto_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avto',
            name='owner',
        ),
        migrations.AddField(
            model_name='avto',
            name='owner',
            field=models.ManyToManyField(null=True, through='project_first_app.Ownership', to='project_first_app.Owner'),
        ),
    ]
