# Generated by Django 3.0.4 on 2020-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_owner_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=40)),
                ('desc', models.TextField(max_length=20)),
                ('places', models.IntegerField(max_length=4)),
                ('types', models.TextField()),
                ('facilities', models.TextField()),
                ('owner', models.TextField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='car',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
    ]
