# Generated by Django 3.0.4 on 2020-04-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='datein',
            field=models.DateField(default='11.12.2013'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dateout',
            field=models.DateField(default='12.12.2013'),
        ),
    ]
