# Generated by Django 3.0.4 on 2020-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0012_auto_20200420_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='din',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dout',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='sergrolo@mail.ru', max_length=254),
            preserve_default=False,
        ),
    ]
