# Generated by Django 3.0.4 on 2020-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0014_auto_20200420_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='datein',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dateout',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='sergrol@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
