# Generated by Django 3.0.7 on 2020-06-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20200626_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=1, help_text='auto fill in'),
        ),
    ]
