# Generated by Django 3.0.7 on 2020-06-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_auto_20200626_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField()),
                ('work_end', models.TimeField()),
                ('bus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Driver')),
                ('route', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Route')),
            ],
        ),
    ]
