# Generated by Django 3.0.7 on 2020-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0016_auto_20200701_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='A', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='surname',
            field=models.CharField(default='A', max_length=30),
        ),
        migrations.AlterField(
            model_name='bus',
            name='reg_plate',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='num',
            field=models.IntegerField(unique=True),
        ),
    ]
