# Generated by Django 3.0.7 on 2020-07-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0021_auto_20200702_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='d_of_b',
            field=models.DateField(null=True),
        ),
    ]
