# Generated by Django 3.0.7 on 2020-07-06 09:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0025_auto_20200705_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunction',
            name='piece_now',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'engine'), (2, 'tyres'), (3, 'oil filter'), (4, 'lights'), (5, 'turn signals'), (6, 'steering wheel'), (7, 'rear-view mirrors'), (8, 'other')], max_length=15, null=True),
        ),
    ]
