# Generated by Django 3.0.7 on 2020-07-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0026_malfunction_piece_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunction',
            name='piece',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='malfunction',
            name='piece_now',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
