# Generated by Django 3.0.4 on 2020-04-19 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_importance', models.IntegerField(max_length=1, verbose_name='Важность (от 1 до 5)')),
                ('text', models.TextField(db_index=True, verbose_name='Текст комментария')),
                ('comment_type', models.CharField(choices=[('question', 'Вопрос по заданию'), ('found_error', 'Найденная ошибка'), ('other', 'Другое')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Предмет')),
                ('body', models.TextField(db_index=True, verbose_name='Текст задания')),
                ('date_issue', models.DateTimeField(verbose_name='Дата выдачи')),
                ('duration', models.DurationField(verbose_name='Период выполнения')),
                ('fines', models.CharField(db_index=True, max_length=150, verbose_name='Информация о штрафах')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw.Comment')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'ordering': ['-date_issue'],
            },
        ),
    ]
