# Generated by Django 3.0.4 on 2020-04-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0002_auto_20200419_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-date_issue'], 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашнее задание'},
        ),
    ]
