# Generated by Django 3.0.4 on 2020-04-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0003_auto_20200419_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date_issue',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
    ]
