# Generated by Django 3.0.4 on 2020-04-19 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0004_auto_20200419_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hw.Homework'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.CharField(default='Ирина Шейх', max_length=150, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='fines',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Информация о штрафах'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Предмет'),
        ),
    ]
