# Generated by Django 3.0.4 on 2020-04-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0006_auto_20200419_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('question', 'Вопрос по заданию'), ('found_error', 'Найденная ошибка'), ('other', 'Другое')], max_length=50, verbose_name='Тип комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hw.Homework', verbose_name='Домашнее задание'),
        ),
    ]
