# Generated by Django 3.0.4 on 2020-04-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0007_auto_20200421_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('question', 'Вопрос по заданию'), ('found_error', 'Найденная ошибка'), ('Другое', 'other')], max_length=50, verbose_name='Тип комментария'),
        ),
    ]
