# Generated by Django 3.0.4 on 2020-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0008_auto_20200421_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('Вопрос по заданию', 'Вопрос по заданию'), ('Найденная ошибка', 'Найденная ошибка'), ('Другое', 'Другое')], max_length=50, verbose_name='Тип комментария'),
        ),
    ]
