# Generated by Django 3.0.4 on 2020-04-22 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0009_auto_20200421_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_importance',
            field=models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Важность (от 1 до 5)'),
        ),
    ]
