# Generated by Django 3.0.4 on 2020-04-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0011_auto_20200424_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='duration',
            field=models.DurationField(verbose_name='Период выполнения'),
        ),
    ]
