# Generated by Django 3.0.5 on 2020-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('facilities', models.CharField(choices=[('wifi', 'Free Wi-Fi'), ('parking', 'Parking space')], max_length=10)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
