# Generated by Django 3.0.5 on 2020-05-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_hotel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='teaser',
            field=models.TextField(default='', max_length=50),
        ),
    ]
