# Generated by Django 3.0.5 on 2020-06-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Awful'), (2, '2 - Unsatisfactory'), (3, '3 - Bad'), (4, '4 - Quite bad'), (5, '5 - Average'), (6, '6 - Alright'), (7, '7 - Quite good'), (8, '8 - Good'), (9, '9 - Great'), (10, '10 - Perfect')], default=5),
        ),
    ]
