# Generated by Django 3.0.5 on 2020-06-16 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vacation_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='comment',
            name='vacation_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
