# Generated by Django 3.0.5 on 2020-06-16 17:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_auto_20200616_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='country',
            field=django_countries.fields.CountryField(default='New Zealand', max_length=2),
        ),
    ]
