# Generated by Django 3.0.5 on 2020-06-16 17:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_comment_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='country',
            field=django_countries.fields.CountryField(default='nz', max_length=2),
        ),
    ]
