# Generated by Django 3.0.5 on 2020-06-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_auto_20200621_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(choices=[(1, '0-10 y.o.'), (2, '10-20 y.o.'), (3, '20-30 y.o.'), (4, '30-40 y.o.'), (5, '40-50 y.o.'), (6, '50-60 y.o.'), (7, '60-70 y.o.'), (8, '70-80 y.o.'), (9, '80-90 y.o.'), (10, '90-... y.o')], default=3),
        ),
    ]
