# Generated by Django 3.0.5 on 2020-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_auto_20200621_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tourist_kind',
            field=models.IntegerField(choices=[(1, 'Business Traveler'), (2, 'Solo Traveler'), (3, 'Couple'), (4, 'Family with Young Children'), (5, 'Family with Teenagers'), (6, 'Group Traveler')], default=2),
        ),
    ]
