# Generated by Django 3.0.5 on 2020-06-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_comment_tourist_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='facilities',
        ),
    ]
