# Generated by Django 3.0.5 on 2020-06-20 22:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_remove_hotel_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('wifi', 'Free Wi-Fi'), ('parking', 'Parking space'), ('nosmoke', 'Non-smoking rooms'), ('ac', 'Air Conditioning'), ('pool', 'Swimming pool'), ('massage', 'Massage'), ('nosound', 'Soundproof rooms')], default='wifi', max_length=44),
        ),
    ]
