# Generated by Django 3.0.7 on 2020-06-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_plate', models.CharField(max_length=6)),
                ('type', models.IntegerField(choices=[(1, 'very little'), (2, 'little'), (3, 'average'), (4, 'big'), (5, 'articulated')])),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='work_exp',
        ),
    ]
