# Generated by Django 3.0.7 on 2020-06-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_bus_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='salary',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='driver',
            name='work_exp',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=1, help_text='fills in based on "Type"'),
        ),
    ]
