# Generated by Django 3.0.7 on 2020-06-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_auto_20200626_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='salary',
            field=models.IntegerField(help_text='fills in based on "Work_exp and Job_class"'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='work_exp',
            field=models.IntegerField(help_text='fills in based on "Date_begin"'),
        ),
    ]
