# Generated by Django 3.0.7 on 2020-06-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_auto_20200626_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='job_class',
            field=models.IntegerField(choices=[(3, 3), (2, 2), (1, 1)]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='salary',
            field=models.IntegerField(help_text='fills in based on "Work exp" and "Job class"'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='work_exp',
            field=models.IntegerField(help_text='fills in based on "Date begin"'),
        ),
    ]
