# Generated by Django 3.0.7 on 2020-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_auto_20200626_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=0, help_text='fills in based on "Type"'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='salary',
            field=models.IntegerField(default=0, help_text='fills in based on "Work exp" and "Job class"'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='work_exp',
            field=models.IntegerField(default=0, help_text='fills in based on "Date begin"'),
        ),
    ]
