# Generated by Django 3.0.7 on 2020-06-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_auto_20200626_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('loc_start', models.CharField(max_length=100)),
                ('loc_end', models.CharField(max_length=100)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('interval', models.DateTimeField()),
                ('circle_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
    ]
