# Generated by Django 3.0.7 on 2020-06-26 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_auto_20200626_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='bus',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bus.Bus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Route'),
            preserve_default=False,
        ),
    ]
