# Generated by Django 3.0.7 on 2020-06-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='circle_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='interval',
        ),
        migrations.AddField(
            model_name='route',
            name='circle_time_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='interval_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
