# Generated by Django 3.0.7 on 2020-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0014_auto_20200701_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='work_start',
        ),
    ]
