# Generated by Django 3.0.7 on 2020-07-02 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0018_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='schedule_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Schedule', unique=True),
        ),
    ]
