# Generated by Django 3.0.7 on 2020-07-02 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0019_auto_20200702_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='schedule_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.Schedule'),
        ),
    ]
