# Generated by Django 3.0.7 on 2020-07-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0020_auto_20200702_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='work_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_start',
            field=models.TimeField(null=True),
        ),
    ]
