# Generated by Django 3.0.7 on 2020-07-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0022_driver_d_of_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='surname',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Malfunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('piece', models.IntegerField()),
                ('date_close', models.DateField(null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Bus')),
            ],
        ),
    ]
