# Generated by Django 3.0.7 on 2020-07-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0023_auto_20200705_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Malfunctions',
            new_name='Malfunction',
        ),
    ]
