# Generated by Django 3.0.7 on 2020-07-05 18:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0024_auto_20200705_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunction',
            name='date_close',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='malfunction',
            name='piece',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'engine'), (2, 'tyres'), (3, 'oil filter'), (4, 'lights'), (5, 'turn signals'), (6, 'steering wheel'), (7, 'rear-view mirrors'), (8, 'other')], max_length=15),
        ),
    ]
