# Generated by Django 3.0.6 on 2020-05-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alpinist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(default='1980-01-01')),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, default='city-street-house-flat', max_length=150)),
            ],
            options={
                'db_table': 'Alpinist',
            },
        ),
        migrations.CreateModel(
            name='Ascent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ascent_code', models.CharField(max_length=30)),
                ('duration', models.TimeField()),
                ('complexity', models.IntegerField(default=5)),
                ('ascent_height', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'Ascent',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=30)),
                ('contact_person', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('group_success', models.CharField(choices=[('Finished', 'Ascent was successfully finished'), ('Not finished', 'Ascent was not finished'), ('Not started', 'Ascent was not started')], max_length=30)),
                ('participant', models.ManyToManyField(to='alpinism.Alpinist')),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain_name', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('height', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinism.Country')),
            ],
            options={
                'db_table': 'Mountain',
            },
        ),
        migrations.CreateModel(
            name='IndSuccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_success', models.CharField(choices=[('Finished', 'Ascent was successfully finished'), ('Injured', 'Ascent was not finished due to the injury'), ('Not finished', 'Ascent was not finished on behalf of the alpinist'), ('Not started', 'Alpinist did not participate')], max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinism.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinism.Alpinist')),
            ],
            options={
                'verbose_name': 'Individual success',
                'verbose_name_plural': 'Individual successes',
                'db_table': 'IndSuccess',
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('situation', models.CharField(choices=[('Injury', 'Alpinist was injured'), ('Gone', 'Alpinist got lost'), ('Death', 'Alpinist died')], max_length=10)),
                ('commentary', models.TextField(max_length=1000)),
                ('ascent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinism.Ascent')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinism.Alpinist')),
            ],
            options={
                'verbose_name_plural': 'Emergencies',
                'db_table': 'Emergency',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('contact_person', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinism.Country')),
            ],
            options={
                'db_table': 'Club',
            },
        ),
        migrations.AddField(
            model_name='ascent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinism.Group'),
        ),
        migrations.AddField(
            model_name='alpinist',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinism.Club'),
        ),
    ]
