# Generated by Django 3.0.6 on 2020-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpinism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascent',
            name='duration',
            field=models.DurationField(),
        ),
    ]
