# Generated by Django 3.0.6 on 2020-07-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpinism', '0002_auto_20200530_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascent',
            name='mountain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alpinism.Mountain'),
            preserve_default=False,
        ),
    ]
