# Generated by Django 3.0.5 on 2020-04-19 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('size', models.CharField(max_length=20, verbose_name='Size')),
                ('rooms', models.CharField(max_length=50, verbose_name='Rooms')),
                ('amenities', models.CharField(max_length=50, verbose_name='Amenities')),
                ('owner', models.CharField(max_length=30, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250, verbose_name='Comment')),
                ('rating', models.CharField(max_length=2, verbose_name='Rating')),
                ('start_date', models.DateField(verbose_name='Arrival')),
                ('end_date', models.DateField(verbose_name='Departure')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted on')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotellist.Hotel')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
