# Generated by Django 3.0.5 on 2020-04-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='vehicles',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Vehicle'),
        ),
    ]
