# Generated by Django 3.0.5 on 2020-04-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.CharField(default='92385', max_length=20),
            preserve_default=False,
        ),
    ]
