# Generated by Django 3.0.5 on 2020-06-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_starting_date', models.DateField(verbose_name='время закрепления')),
                ('attachment_finishing_date', models.DateField(null=True, verbose_name='время открепления')),
            ],
            options={
                'verbose_name': 'Закрепление',
                'verbose_name_plural': 'Закрепления',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('author', models.CharField(max_length=100, verbose_name='автор(ы)')),
                ('publisher', models.CharField(max_length=50, verbose_name='издатель')),
                ('edition_year', models.SmallIntegerField(verbose_name='год издания')),
                ('sphere', models.CharField(max_length=30, verbose_name='раздел')),
                ('cipher', models.CharField(max_length=20, verbose_name='шифр книги')),
                ('receipt_date', models.DateField(verbose_name='дата поступления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14, verbose_name='название')),
                ('capacity', models.SmallIntegerField(verbose_name='вместимость (человек)')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_card_num', models.CharField(max_length=8, verbose_name='номер читательского билета')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('passport_data', models.CharField(max_length=10, verbose_name='серия, номер паспорта')),
                ('edition_year', models.SmallIntegerField(verbose_name='год издания')),
                ('birth_date', models.DateField(verbose_name='дата рождения')),
                ('home_address', models.TextField(verbose_name='адрес')),
                ('phone_num', models.CharField(max_length=12, verbose_name='контактный номер')),
                ('education', models.CharField(choices=[('среднее общее', 'среднее общее'), ('среднее профессиональное', 'среднее профессиональное'), ('неполное высшее', 'неполное высшее'), ('бакалавр', 'бакалавр'), ('специалист', 'специалист'), ('магистр', 'магистр'), ('аспирантура', 'аспирантура')], max_length=24, verbose_name='образование')),
                ('degree', models.BooleanField(verbose_name='наличие учёной степени')),
                ('books', models.ManyToManyField(related_name='reader', through='lib_app.Attachment', to='lib_app.Book', verbose_name='книги')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.Hall', verbose_name='зал')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.Hall', verbose_name='зал'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.Book', verbose_name='книга'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.Reader', verbose_name='читатель'),
        ),
    ]
