# Generated by Django 3.0.5 on 2020-06-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0005_auto_20200621_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(verbose_name='название'),
        ),
    ]
