# Generated by Django 2.0.2 on 2020-06-20 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, verbose_name='Comment')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Rating')),
                ('start', models.DateField(verbose_name='Arrival')),
                ('end', models.DateField(verbose_name='Departure')),
                ('post', models.DateTimeField(auto_now_add=True, verbose_name='Posted on')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('capacity', models.CharField(max_length=20, verbose_name='Capacity')),
                ('rooms', models.CharField(max_length=50, verbose_name='Rooms')),
                ('comfort', models.CharField(max_length=50, verbose_name='Comfort')),
                ('owner', models.CharField(max_length=30, verbose_name='Owner')),
            ],
            options={
                'db_table': 'Hotel',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.Hotel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
