# Generated by Django 2.0.2 on 2020-06-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0002_auto_20200621_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='capacity',
            field=models.CharField(max_length=500, verbose_name='Capacity'),
        ),
    ]
