# Generated by Django 3.0.5 on 2020-04-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20200415_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
