# Generated by Django 3.0.4 on 2020-04-19 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=50, verbose_name='Название турагентства')),
            ],
            options={
                'verbose_name': 'Турагентство',
                'verbose_name_plural': 'Турагентства',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.CharField(max_length=50, verbose_name='Название тура')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('period_s', models.DateField(verbose_name='Период тура с')),
                ('period_po', models.DateField(verbose_name='Период тура по')),
                ('summa', models.CharField(max_length=50, verbose_name='Стоимость тура')),
                ('text_of_tour', models.CharField(max_length=5000, verbose_name='Описание тура')),
                ('conditions', models.CharField(max_length=5000, verbose_name='Условия оплаты')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_agency.Agency')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('country_live', models.CharField(max_length=50, verbose_name='Страна проживания')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_comment', models.CharField(blank=True, choices=[('Вопрос_по_содержанию_тура', 'Вопрос По Содержанию Тура'), ('Вопрос_об_условиях_оплаты', 'Вопрос Об Условиях Оплаты'), ('Отзыв', 'Отзыв')], max_length=50, verbose_name='Тип комментария')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст комментария')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_agency.Tours', verbose_name='Тур')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_agency.Tourist', verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
