# Generated by Django 3.0.4 on 2020-04-19 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour_agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tourist',
            new_name='UserProfile',
        ),
    ]
