# Generated by Django 3.0.4 on 2020-04-19 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour_agency', '0002_auto_20200419_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
    ]
