# Generated by Django 3.0 on 2020-06-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20200619_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Зачислен', 'Зачислен'), ('В_очереди', 'В Очереди'), ('Не_зачислен', 'Не Зачислен')], max_length=100, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='attestatsubject',
            name='attestat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='college.Attestat'),
        ),
        migrations.AlterField(
            model_name='egesubject',
            name='ege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='college.EGE'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название специальности'),
        ),
    ]
