# Generated by Django 3.0 on 2020-06-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20200619_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestat',
            name='enrollee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestat', to='college.Enrollee'),
        ),
    ]
