# Generated by Django 3.0 on 2020-06-22 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_application_form_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='profile',
        ),
        migrations.AddField(
            model_name='specialty',
            name='faculty',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='college.Faculty'),
            preserve_default=False,
        ),
    ]
