# Generated by Django 3.0.6 on 2020-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
