from django.urls import path
from . import views

urlpatterns = [
    path("attestat/", views.AttestatViewSet.as_view({'get': 'list'})),
    path("attestat/<int:pk>/", views.AttestatViewSet.as_view({'get': 'retrieve'})),
    path("attestat/create", views.AttestatViewSet.as_view({'post': 'create'})),
    path("attestat/<int:pk>/update", views.AttestatViewSet.as_view({'post': 'update'})),
    path("attestat/<int:pk>/delete", views.AttestatViewSet.as_view({'delete': 'destroy'})),
    path("ege/", views.EgeViewSet.as_view({'get': 'list'})),
    path("ege/<int:pk>/", views.EgeViewSet.as_view({'get': 'retrieve'})),
    path("ege/create", views.EgeViewSet.as_view({'post': 'create'})),
    path("ege/<int:pk>/update", views.EgeViewSet.as_view({'post': 'update'})),
    path("ege/<int:pk>/delete", views.EgeViewSet.as_view({'delete': 'destroy'})),
    path("application/", views.ApplicationViewSet.as_view({'get': 'list'})),
    path("application/<int:pk>/", views.ApplicationViewSet.as_view({'get': 'retrieve'})),
    path("application/create", views.ApplicationViewSet.as_view({'post': 'create'})),
    path("application/<int:pk>/update", views.ApplicationViewSet.as_view({'post': 'update'})),
    path("application/<int:pk>/delete", views.ApplicationViewSet.as_view({'delete': 'destroy'})),
    path("enrollee/", views.EnrolleeViewSet.as_view({'get': 'list'})),
    path("enrollee/<int:pk>/", views.EnrolleeViewSet.as_view({'get': 'retrieve'})),
    path("enrollee/create", views.EnrolleeViewSet.as_view({'post': 'create'})),
    path("enrollee/<int:pk>/update", views.EnrolleeViewSet.as_view({'post': 'update'})),
    path("enrollee/<int:pk>/delete", views.EnrolleeViewSet.as_view({'delete': 'destroy'})),
    path("egesubject/", views.EgeSubjectViewSet.as_view({'get': 'list'})),
    path("egesubject/<int:pk>/", views.EgeSubjectViewSet.as_view({'get': 'retrieve'})),
    path("egesubject/create", views.EgeSubjectViewSet.as_view({'post': 'create'})),
    path("egesubject/<int:pk>/delete", views.EgeSubjectViewSet.as_view({'delete': 'destroy'})),
    path("attestatsubject/", views.AttestatSubjectViewSet.as_view({'get': 'list'})),
    path("attestatsubject/<int:pk>/", views.AttestatSubjectViewSet.as_view({'get': 'retrieve'})),
    path("attestatsubject/create", views.AttestatSubjectViewSet.as_view({'post': 'create'})),
    path("attestatsubject/<int:pk>/delete", views.AttestatSubjectViewSet.as_view({'delete': 'destroy'})),
    path("specialty/", views.SpecialtyViewSet.as_view({'get': 'list'})),
    path("specialty/<int:pk>/", views.SpecialtyViewSet.as_view({'get': 'retrieve'})),
    path("faculty/", views.FacultyViewSet.as_view({'get': 'list'})),
    path("faculty/<int:pk>/", views.FacultyViewSet.as_view({'get': 'retrieve'})),
    path('query1/', views.Query1.as_view()),
    path('query2/', views.Query2.as_view()),
    path('query3/', views.Query3.as_view()),
    path('query4/', views.Query4.as_view()),
]