# Generated by Django 3.0 on 2020-10-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер государственной регистрации автобуса,')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=100, verbose_name='Тип автобуса по габариам')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Тип автобуса',
                'verbose_name_plural': 'Типы автобусов',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('driver_class', models.CharField(blank=True, choices=[('1_класс', '1 Класс'), ('2_класс', '2 Класс'), ('3_класс', '3 Класс')], max_length=20, verbose_name='Водительский класс')),
                ('work_exp', models.IntegerField(verbose_name='Стаж работы')),
                ('salary', models.IntegerField(verbose_name='Оклад')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=300, verbose_name='Начальный пункт движения')),
                ('final_destination', models.CharField(max_length=300, verbose_name='Конечный пункт движения')),
                ('time_start', models.TimeField(verbose_name='Время начала движения')),
                ('time_end', models.TimeField(verbose_name='Время окончания движения')),
                ('interval_of_movement', models.IntegerField(verbose_name='Интервал движения в минутах')),
                ('length_in_min', models.IntegerField(verbose_name='Протяженность в минутах')),
                ('length_in_km', models.IntegerField(verbose_name='Протяженность в километрах')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, verbose_name='День недели')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_depot.Bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_depot.Driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_depot.Route')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Вышел_на_линию', 'Вышел На Линию'), ('Не_вышел_на_линию', 'Не Вышел На Линию')], max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_depot.Schedule')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_depot.BusType'),
        ),
    ]
