# Generated by Django 3.0 on 2020-10-10 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_depot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер государственной регистрации автобуса'),
        ),
    ]
