# Generated by Django 3.0.4 on 2020-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslicense',
            name='type',
            field=models.CharField(choices=[('A', 'Motorcycles'), ('A1', 'Light motorcycles'), ('B', 'Passenger cars, small trucks (up to 3.5 tons)'), ('BE', 'Passenger cars with a trailer'), ('B1', 'Tricycles'), ('C', 'Commercial vehicles (from 3.5 tonnes)'), ('CE', 'Trucks with a trailer'), ('C1', 'Medium trucks (from 3.5 to 7.5 tons)'), ('C1E', 'Medium trucks with trailer'), ('D', 'Buses'), ('DE', 'Buses with a trailer'), ('D1', 'Small buses'), ('D1E', 'Small buses with a trailer'), ('M', 'Mopeds'), ('Tm', 'Trams'), ('Tb', 'Trolleybuses')], max_length=3),
        ),
    ]
