# Generated by Django 3.0.4 on 2020-03-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_auto_20200321_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='members',
            new_name='owners',
        ),
    ]
