# Generated by Django 3.0.4 on 2020-03-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_auto_20200321_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverslicense',
            old_name='type',
            new_name='category',
        ),
    ]
