# Generated by Django 3.0.4 on 2020-03-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_auto_20200321_1934'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='Car',
        ),
        migrations.AlterModelTable(
            name='driverslicense',
            table='DriversLicense',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='Owner',
        ),
        migrations.AlterModelTable(
            name='ownership',
            table='Ownership',
        ),
    ]
