# Generated by Django 3.0.7 on 2020-06-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturient',
            name='marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='сумма оценок'),
        ),
    ]
