# Generated by Django 3.0.7 on 2020-07-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abit', '0002_auto_20200630_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturient',
            name='abit_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'после 9'), (2, 'после 11')], default=2, verbose_name='тип поступления'),
        ),
    ]
