# Generated by Django 3.0.4 on 2020-04-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racer',
            old_name='grade_of_licence',
            new_name='grade_of_license',
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.AddField(
            model_name='racer',
            name='car',
            field=models.OneToOneField(default='IA', on_delete=django.db.models.deletion.CASCADE, to='board.Car'),
            preserve_default=False,
        ),
    ]
