# Generated by Django 3.0.4 on 2020-04-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racer',
            old_name='team_name',
            new_name='team',
        ),
    ]
