# Generated by Django 3.0.4 on 2020-04-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racer',
            old_name='grade_of_license',
            new_name='grade_of_licence',
        ),
        migrations.RemoveField(
            model_name='racer',
            name='id',
        ),
        migrations.AlterField(
            model_name='racer',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='board.Car'),
        ),
    ]
