# Generated by Django 3.0.4 on 2020-04-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200417_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='racer',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
