# Generated by Django 3.0.4 on 2020-04-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200417_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racer',
            old_name='grade_of_licence',
            new_name='grade_of_license',
        ),
    ]
