# Generated by Django 3.0.4 on 2020-04-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200417_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Racer')),
            ],
            options={
                'db_table': 'Race',
            },
        ),
    ]
