# Generated by Django 3.0.4 on 2020-04-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='grade_of_license',
            field=models.CharField(choices=[('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Grade C', 'Grade C'), ('International Grade A', 'International Grade A'), ('International Grade B', 'International Grade B'), ('International Grade C', 'International Grade C')], max_length=21),
        ),
    ]
