# Generated by Django 3.0.4 on 2020-04-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20200418_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.CharField(choices=[('Collaboration', 'Collaboration'), ('Race', 'Race'), ('Other', 'Other')], max_length=13),
        ),
    ]
