# Generated by Django 3.0.6 on 2020-05-31 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Дата приема')),
            ],
        ),
        migrations.CreateModel(
            name='App_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Начало времени приема')),
                ('time_end', models.TimeField(verbose_name='Окончание времени приема')),
                ('appointment_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.App_date')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('education', models.CharField(max_length=300, verbose_name='Образование')),
                ('category', models.CharField(choices=[('1', 'Врач 1-ой категории'), ('2', 'Врач 2-ой категории'), ('3', 'Врач 3-ей категории')], max_length=1, verbose_name='Категория врача')),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.Doctor')),
                ('work_time', models.ManyToManyField(to='hospital_app.App_time')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.TextField(verbose_name='Диагноз и лечение')),
                ('date', models.DateField(verbose_name='Дата назначения')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.Doctor', verbose_name='Лечащий врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.Patient', verbose_name='Пациент')),
            ],
        ),
    ]
