# Generated by Django 3.0.6 on 2020-06-02 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_appointment'),
    ]

    atomic = False

    operations = [
        migrations.CreateModel(
            name='App_times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Начало времени приема')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата приема'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время приема'),
        ),
        migrations.RenameModel(
            old_name='App_date',
            new_name='App_dates',
        ),
        migrations.DeleteModel(
            name='App_time',
        ),
        migrations.AddField(
            model_name='app_times',
            name='appointment_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.App_dates'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_time',
            field=models.ManyToManyField(to='hospital_app.App_times'),
        ),
    ]
