# Generated by Django 3.0.6 on 2020-06-05 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_auto_20200602_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_times',
            name='time_start',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Начало времени приема'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время приема'),
        ),
    ]
