# Generated by Django 3.0.6 on 2020-06-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0008_auto_20200618_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='doc',
            new_name='doctor',
        ),
    ]
