# Generated by Django 3.0.4 on 2020-05-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('Marka', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Colour', models.CharField(max_length=50)),
                ('Auto_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('Owner', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Surname', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Udostoverenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kateblog.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Ownship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_end', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Auto_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kateblog.Auto')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kateblog.Owner')),
            ],
        ),
    ]
