# Generated by Django 3.0.4 on 2020-05-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kateblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Owner',
            new_name='Owner_id',
        ),
        migrations.RenameField(
            model_name='ownship',
            old_name='Owner',
            new_name='Owner_id',
        ),
        migrations.RenameField(
            model_name='udostoverenie',
            old_name='Owner',
            new_name='Owner_id',
        ),
    ]
