# Generated by Django 3.0.4 on 2020-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kateblog', '0002_auto_20200517_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Date',
            new_name='Date_of_birth',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Owner_id',
            new_name='Owner_name',
        ),
        migrations.RenameField(
            model_name='ownship',
            old_name='Date',
            new_name='Date_start',
        ),
        migrations.RenameField(
            model_name='ownship',
            old_name='Owner_id',
            new_name='Owner_name',
        ),
        migrations.RenameField(
            model_name='udostoverenie',
            old_name='Owner_id',
            new_name='Owner_name',
        ),
        migrations.RemoveField(
            model_name='udostoverenie',
            name='id',
        ),
        migrations.AlterField(
            model_name='udostoverenie',
            name='Number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
