# Generated by Django 3.0.4 on 2020-05-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kateblog', '0003_auto_20200517_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='Date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownship',
            name='Date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownship',
            name='Date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='udostoverenie',
            name='Date',
            field=models.DateField(),
        ),
    ]
