# Generated by Django 3.0.4 on 2020-05-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kateblog', '0004_auto_20200517_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownship',
            old_name='Owner_name',
            new_name='Owner_n',
        ),
        migrations.RenameField(
            model_name='udostoverenie',
            old_name='Owner_name',
            new_name='Owner_names',
        ),
    ]
