# Generated by Django 3.0.4 on 2020-05-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kateblog', '0005_auto_20200521_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='autos',
            field=models.ManyToManyField(through='Kateblog.Ownship', to='Kateblog.Auto'),
        ),
    ]