# Generated by Django 3.1.2 on 2020-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencing_publications', '0003_auto_20201025_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorduties',
            name='date_begin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directorduties',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
