# Generated by Django 3.1.2 on 2020-10-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presencing_publications', '0006_book_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='orig_lang_name',
            new_name='orig_lang_title',
        ),
    ]
